create fact notification as
select
    t.event_date::date as __date__,
    *
from dma.vo_notification t
;

create metrics notification as
select
    sum(browser_pushes_no_data) as browser_push_no_data,
    sum(browser_pushes_open) as browser_push_open,
    sum(browser_pushes_prepared) as browser_push_prepared,
    sum(browser_pushes_to_provider) as browser_push_to_provider,
    sum(browser_pushes_to_receiver) as browser_push_to_receiver,
    sum(email_action) as email_action,
    sum(email_no_data) as email_no_data,
    sum(email_open) as email_open,
    sum(email_prepared) as email_prepared,
    sum(email_to_provider) as email_to_provider,
    sum(email_to_receiver) as email_to_receiver,
    sum(notification_center_action) as nc_action,
    sum(notification_center_no_data) as nc_no_data,
    sum(notification_center_open) as nc_open,
    sum(notification_center_prepared) as nc_prepared,
    sum(notification_center_to_provider) as nc_to_provider,
    sum(notification_center_to_receiver) as nc_to_receiver,
    sum(app_pushes_no_data) as push_no_data,
    sum(app_pushes_open) as push_open,
    sum(app_pushes_prepared) as push_prepared,
    sum(app_pushes_price_all_no_data) as push_price_all_no_data,
    sum(app_pushes_price_all_open) as push_price_all_open,
    sum(app_pushes_price_all_prepared) as push_price_all_prepared,
    sum(app_pushes_price_all_to_provider) as push_price_all_to_provider,
    sum(app_pushes_price_all_to_receiver) as push_price_all_to_receiver,
    sum(app_pushes_price_no_data) as push_price_no_data,
    sum(app_pushes_price_open) as push_price_open,
    sum(app_pushes_price_prepared) as push_price_prepared,
    sum(app_pushes_price_to_provider) as push_price_to_provider,
    sum(app_pushes_price_to_receiver) as push_price_to_receiver,
    sum(app_pushes_rec_marketing_no_data) as push_rec_marketing_no_data,
    sum(app_pushes_rec_marketing_open) as push_rec_marketing_open,
    sum(app_pushes_rec_marketing_prepared) as push_rec_marketing_prepared,
    sum(app_pushes_rec_marketing_to_provider) as push_rec_marketing_to_provider,
    sum(app_pushes_rec_marketing_to_receiver) as push_rec_marketing_to_receiver,
    sum(app_pushes_sav_search_no_data) as push_sav_search_no_data,
    sum(app_pushes_sav_search_open) as push_sav_search_open,
    sum(app_pushes_sav_search_prepared) as push_sav_search_prepared,
    sum(app_pushes_sav_search_to_provider) as push_sav_search_to_provider,
    sum(app_pushes_sav_search_to_receiver) as push_sav_search_to_receiver,
    sum(app_pushes_to_provider) as push_to_provider,
    sum(app_pushes_to_receiver) as push_to_receiver,
    sum(sms_delivered_action) as sms_action,
    sum(sms_no_data) as sms_no_data,
    sum(sms_delivered_open) as sms_open,
    sum(sms_prepared) as sms_prepared,
    sum(sms_to_provider) as sms_to_provider,
    sum(sms_delivered_to_receiver) as sms_to_receiver
from notification t
;

create metrics notification_participant as
select
    sum(case when browser_push_no_data > 0 then 1 end) as user_browser_push_no_data,
    sum(case when browser_push_open > 0 then 1 end) as user_browser_push_open,
    sum(case when browser_push_prepared > 0 then 1 end) as user_browser_push_prepared,
    sum(case when browser_push_to_provider > 0 then 1 end) as user_browser_push_to_provider,
    sum(case when browser_push_to_receiver > 0 then 1 end) as user_browser_push_to_receiver,
    sum(case when email_action > 0 then 1 end) as user_email_action,
    sum(case when email_no_data > 0 then 1 end) as user_email_no_data,
    sum(case when email_open > 0 then 1 end) as user_email_open,
    sum(case when email_prepared > 0 then 1 end) as user_email_prepared,
    sum(case when email_to_provider > 0 then 1 end) as user_email_to_provider,
    sum(case when email_to_receiver > 0 then 1 end) as user_email_to_receiver,
    sum(case when nc_action > 0 then 1 end) as user_nc_action,
    sum(case when nc_no_data > 0 then 1 end) as user_nc_no_data,
    sum(case when nc_open > 0 then 1 end) as user_nc_open,
    sum(case when nc_prepared > 0 then 1 end) as user_nc_prepared,
    sum(case when nc_to_provider > 0 then 1 end) as user_nc_to_provider,
    sum(case when nc_to_receiver > 0 then 1 end) as user_nc_to_receiver,
    sum(case when push_no_data > 0 then 1 end) as user_push_no_data,
    sum(case when push_price_no_data > 0 then 1 end) as user_push_no_data_price,
    sum(case when push_price_all_no_data > 0 then 1 end) as user_push_no_data_price_all,
    sum(case when push_rec_marketing_no_data > 0 then 1 end) as user_push_no_data_rec_marketing,
    sum(case when push_sav_search_no_data > 0 then 1 end) as user_push_no_data_sav,
    sum(case when push_open > 0 then 1 end) as user_push_open,
    sum(case when push_price_open > 0 then 1 end) as user_push_open_price,
    sum(case when push_price_all_open > 0 then 1 end) as user_push_open_price_all,
    sum(case when push_rec_marketing_open > 0 then 1 end) as user_push_open_rec_marketing,
    sum(case when push_sav_search_open > 0 then 1 end) as user_push_open_sav,
    sum(case when push_prepared > 0 then 1 end) as user_push_prepared,
    sum(case when push_price_prepared > 0 then 1 end) as user_push_prepared_price,
    sum(case when push_price_all_prepared > 0 then 1 end) as user_push_prepared_price_all,
    sum(case when push_rec_marketing_prepared > 0 then 1 end) as user_push_prepared_rec_marketing,
    sum(case when push_sav_search_prepared > 0 then 1 end) as user_push_prepared_sav,
    sum(case when push_to_provider > 0 then 1 end) as user_push_to_provider,
    sum(case when push_price_to_provider > 0 then 1 end) as user_push_to_provider_price,
    sum(case when push_price_all_to_provider > 0 then 1 end) as user_push_to_provider_price_all,
    sum(case when push_rec_marketing_to_provider > 0 then 1 end) as user_push_to_provider_rec_marketing,
    sum(case when push_sav_search_to_provider > 0 then 1 end) as user_push_to_provider_sav,
    sum(case when push_to_receiver > 0 then 1 end) as user_push_to_receiver,
    sum(case when push_price_to_receiver > 0 then 1 end) as user_push_to_receiver_price,
    sum(case when push_price_all_to_receiver > 0 then 1 end) as user_push_to_receiver_price_all,
    sum(case when push_rec_marketing_to_receiver > 0 then 1 end) as user_push_to_receiver_rec_marketing,
    sum(case when push_sav_search_to_receiver > 0 then 1 end) as user_push_to_receiver_sav,
    sum(case when sms_action > 0 then 1 end) as user_sms_action,
    sum(case when sms_no_data > 0 then 1 end) as user_sms_no_data,
    sum(case when sms_open > 0 then 1 end) as user_sms_open,
    sum(case when sms_prepared > 0 then 1 end) as user_sms_prepared,
    sum(case when sms_to_provider > 0 then 1 end) as user_sms_to_provider,
    sum(case when sms_to_receiver > 0 then 1 end) as user_sms_to_receiver
from (
    select
        cookie_id, participant_id,
        sum(browser_pushes_no_data) as browser_push_no_data,
        sum(browser_pushes_open) as browser_push_open,
        sum(browser_pushes_prepared) as browser_push_prepared,
        sum(browser_pushes_to_provider) as browser_push_to_provider,
        sum(browser_pushes_to_receiver) as browser_push_to_receiver,
        sum(email_action) as email_action,
        sum(email_no_data) as email_no_data,
        sum(email_open) as email_open,
        sum(email_prepared) as email_prepared,
        sum(email_to_provider) as email_to_provider,
        sum(email_to_receiver) as email_to_receiver,
        sum(notification_center_action) as nc_action,
        sum(notification_center_no_data) as nc_no_data,
        sum(notification_center_open) as nc_open,
        sum(notification_center_prepared) as nc_prepared,
        sum(notification_center_to_provider) as nc_to_provider,
        sum(notification_center_to_receiver) as nc_to_receiver,
        sum(app_pushes_no_data) as push_no_data,
        sum(app_pushes_open) as push_open,
        sum(app_pushes_prepared) as push_prepared,
        sum(app_pushes_price_all_no_data) as push_price_all_no_data,
        sum(app_pushes_price_all_open) as push_price_all_open,
        sum(app_pushes_price_all_prepared) as push_price_all_prepared,
        sum(app_pushes_price_all_to_provider) as push_price_all_to_provider,
        sum(app_pushes_price_all_to_receiver) as push_price_all_to_receiver,
        sum(app_pushes_price_no_data) as push_price_no_data,
        sum(app_pushes_price_open) as push_price_open,
        sum(app_pushes_price_prepared) as push_price_prepared,
        sum(app_pushes_price_to_provider) as push_price_to_provider,
        sum(app_pushes_price_to_receiver) as push_price_to_receiver,
        sum(app_pushes_rec_marketing_no_data) as push_rec_marketing_no_data,
        sum(app_pushes_rec_marketing_open) as push_rec_marketing_open,
        sum(app_pushes_rec_marketing_prepared) as push_rec_marketing_prepared,
        sum(app_pushes_rec_marketing_to_provider) as push_rec_marketing_to_provider,
        sum(app_pushes_rec_marketing_to_receiver) as push_rec_marketing_to_receiver,
        sum(app_pushes_sav_search_no_data) as push_sav_search_no_data,
        sum(app_pushes_sav_search_open) as push_sav_search_open,
        sum(app_pushes_sav_search_prepared) as push_sav_search_prepared,
        sum(app_pushes_sav_search_to_provider) as push_sav_search_to_provider,
        sum(app_pushes_sav_search_to_receiver) as push_sav_search_to_receiver,
        sum(app_pushes_to_provider) as push_to_provider,
        sum(app_pushes_to_receiver) as push_to_receiver,
        sum(sms_delivered_action) as sms_action,
        sum(sms_no_data) as sms_no_data,
        sum(sms_delivered_open) as sms_open,
        sum(sms_prepared) as sms_prepared,
        sum(sms_to_provider) as sms_to_provider,
        sum(sms_delivered_to_receiver) as sms_to_receiver
    from notification t
    group by cookie_id, participant_id
) _
;
