create fact notification_availability as
select
    t.event_date::date as __date__,
    *
from dma.crm_notification_settings_by_user t
;

create metrics notification_availability as
select
    sum(case when (is_any_app_push_default_setting_available = True or is_any_email_default_setting_available = True or is_any_messenger_default_setting_available = True) then 1 end) as any_channel_default_settings_available,
    sum(case when (marketing_app_push_received > 0 or marketing_email_received > 0 or marketing_messenger_received > 0 or marketing_nc_received > 0) then 1 end) as any_channel_marketing_received,
    sum(case when (is_any_app_push_nondefault_setting_available = True or is_any_email_nondefault_setting_available = True or is_any_messenger_nondefault_setting_available = True) then 1 end) as any_channel_nondefault_settings_available,
    sum(case when (rec_app_push_received > 0 or rec_email_received > 0 or rec_messenger_received > 0 or rec_nc_received > 0) then 1 end) as any_channel_rec_received,
    sum(case when (app_push_received > 0 or email_received > 0 or messenger_received > 0 or nc_received > 0) then 1 end) as any_channel_received,
    sum(case when (is_any_app_push_setting_available = True or is_any_email_setting_available = True or is_any_messenger_setting_available = True or is_any_nc_setting_available = True) then 1 end) as any_channel_settings_available,
    sum(case when is_any_app_push_setting_available = True and is_app_push_tech_available = True then 1 end) as app_push_available,
    sum(case when is_any_app_push_default_setting_available = True then 1 end) as app_push_default_settings_available,
    sum(case when marketing_app_push_received > 0 then 1 end) as app_push_marketing_received,
    sum(case when is_any_app_push_nondefault_setting_available = True then 1 end) as app_push_nondefault_settings_available,
    sum(case when rec_app_push_received > 0 then 1 end) as app_push_rec_received,
    sum(case when app_push_received > 0 then 1 end) as app_push_received,
    sum(case when is_any_app_push_setting_available = True then 1 end) as app_push_settings_available,
    sum(case when is_app_push_tech_available = True then 1 end) as app_push_tech_available,
    sum(case when is_any_email_setting_available = True and is_email_tech_available = True then 1 end) as email_available,
    sum(case when is_any_email_default_setting_available = True then 1 end) as email_default_settings_available,
    sum(case when marketing_email_received > 0 then 1 end) as email_marketing_received,
    sum(case when is_any_email_nondefault_setting_available = True then 1 end) as email_nondefault_settings_available,
    sum(case when rec_email_received > 0 then 1 end) as email_rec_received,
    sum(case when email_received > 0 then 1 end) as email_received,
    sum(case when is_any_email_setting_available = True then 1 end) as email_settings_available,
    sum(case when is_email_tech_available = True then 1 end) as email_tech_available,
    sum(case when is_any_messenger_setting_available = True and is_messenger_tech_available = True then 1 end) as messenger_available,
    sum(case when is_any_messenger_default_setting_available = True then 1 end) as messenger_default_settings_available,
    sum(case when marketing_messenger_received > 0 then 1 end) as messenger_marketing_received,
    sum(case when is_any_messenger_nondefault_setting_available = True then 1 end) as messenger_nondefault_settings_available,
    sum(case when rec_messenger_received > 0 then 1 end) as messenger_rec_received,
    sum(case when messenger_received > 0 then 1 end) as messenger_received,
    sum(case when is_any_messenger_setting_available = True then 1 end) as messenger_settings_available,
    sum(case when is_messenger_tech_available = True then 1 end) as messenger_tech_available,
    sum(case when is_any_nc_setting_available = True and is_nc_tech_available = True then 1 end) as nc_available,
    sum(case when marketing_nc_received > 0 then 1 end) as nc_marketing_received,
    sum(case when rec_nc_received > 0 then 1 end) as nc_rec_received,
    sum(case when nc_received > 0 then 1 end) as nc_received,
    sum(case when is_any_nc_setting_available = True then 1 end) as nc_settings_available,
    sum(case when is_nc_tech_available = True then 1 end) as nc_tech_available
from notification_availability t
;

create metrics notification_availability_participant as
select
    sum(case when any_channel_default_settings_available > 0 then 1 end) as user_any_default_setting_available,
    sum(case when any_channel_nondefault_settings_available > 0 then 1 end) as user_any_nondefault_setting_available,
    sum(case when any_channel_settings_available > 0 then 1 end) as user_any_setting_available,
    sum(case when app_push_default_settings_available > 0 then 1 end) as user_app_push_any_default_setting_available,
    sum(case when app_push_nondefault_settings_available > 0 then 1 end) as user_app_push_any_nondefault_setting_available,
    sum(case when app_push_settings_available > 0 then 1 end) as user_app_push_any_setting_available,
    sum(case when app_push_available > 0 then 1 end) as user_app_push_available,
    sum(case when app_push_received > 0 then 1 end) as user_app_push_crm_covered,
    sum(case when app_push_marketing_received > 0 then 1 end) as user_app_push_marketing_crm_covered,
    sum(case when app_push_rec_received > 0 then 1 end) as user_app_push_rec_crm_covered,
    sum(case when app_push_tech_available > 0 then 1 end) as user_app_push_tech_available,
    sum(case when any_channel_received > 0 then 1 end) as user_crm_covered,
    sum(case when email_default_settings_available > 0 then 1 end) as user_email_any_default_setting_available,
    sum(case when email_nondefault_settings_available > 0 then 1 end) as user_email_any_nondefault_setting_available,
    sum(case when email_settings_available > 0 then 1 end) as user_email_any_setting_available,
    sum(case when email_available > 0 then 1 end) as user_email_available,
    sum(case when email_received > 0 then 1 end) as user_email_crm_covered,
    sum(case when email_marketing_received > 0 then 1 end) as user_email_marketing_crm_covered,
    sum(case when email_rec_received > 0 then 1 end) as user_email_rec_crm_covered,
    sum(case when email_tech_available > 0 then 1 end) as user_email_tech_available,
    sum(case when any_channel_marketing_received > 0 then 1 end) as user_marketing_crm_covered,
    sum(case when messenger_default_settings_available > 0 then 1 end) as user_messenger_any_default_setting_available,
    sum(case when messenger_nondefault_settings_available > 0 then 1 end) as user_messenger_any_nondefault_setting_available,
    sum(case when messenger_settings_available > 0 then 1 end) as user_messenger_any_setting_available,
    sum(case when messenger_available > 0 then 1 end) as user_messenger_available,
    sum(case when messenger_received > 0 then 1 end) as user_messenger_crm_covered,
    sum(case when messenger_marketing_received > 0 then 1 end) as user_messenger_marketing_crm_covered,
    sum(case when messenger_rec_received > 0 then 1 end) as user_messenger_rec_crm_covered,
    sum(case when messenger_tech_available > 0 then 1 end) as user_messenger_tech_available,
    sum(case when nc_settings_available > 0 then 1 end) as user_nc_any_setting_available,
    sum(case when nc_available > 0 then 1 end) as user_nc_available,
    sum(case when nc_received > 0 then 1 end) as user_nc_crm_covered,
    sum(case when nc_marketing_received > 0 then 1 end) as user_nc_marketing_crm_covered,
    sum(case when nc_rec_received > 0 then 1 end) as user_nc_rec_crm_covered,
    sum(case when nc_tech_available > 0 then 1 end) as user_nc_tech_available,
    sum(case when any_channel_rec_received > 0 then 1 end) as user_recommendations_crm_covered
from (
    select
        user_id,
        sum(case when (is_any_app_push_default_setting_available = True or is_any_email_default_setting_available = True or is_any_messenger_default_setting_available = True) then 1 end) as any_channel_default_settings_available,
        sum(case when (marketing_app_push_received > 0 or marketing_email_received > 0 or marketing_messenger_received > 0 or marketing_nc_received > 0) then 1 end) as any_channel_marketing_received,
        sum(case when (is_any_app_push_nondefault_setting_available = True or is_any_email_nondefault_setting_available = True or is_any_messenger_nondefault_setting_available = True) then 1 end) as any_channel_nondefault_settings_available,
        sum(case when (rec_app_push_received > 0 or rec_email_received > 0 or rec_messenger_received > 0 or rec_nc_received > 0) then 1 end) as any_channel_rec_received,
        sum(case when (app_push_received > 0 or email_received > 0 or messenger_received > 0 or nc_received > 0) then 1 end) as any_channel_received,
        sum(case when (is_any_app_push_setting_available = True or is_any_email_setting_available = True or is_any_messenger_setting_available = True or is_any_nc_setting_available = True) then 1 end) as any_channel_settings_available,
        sum(case when is_any_app_push_setting_available = True and is_app_push_tech_available = True then 1 end) as app_push_available,
        sum(case when is_any_app_push_default_setting_available = True then 1 end) as app_push_default_settings_available,
        sum(case when marketing_app_push_received > 0 then 1 end) as app_push_marketing_received,
        sum(case when is_any_app_push_nondefault_setting_available = True then 1 end) as app_push_nondefault_settings_available,
        sum(case when rec_app_push_received > 0 then 1 end) as app_push_rec_received,
        sum(case when app_push_received > 0 then 1 end) as app_push_received,
        sum(case when is_any_app_push_setting_available = True then 1 end) as app_push_settings_available,
        sum(case when is_app_push_tech_available = True then 1 end) as app_push_tech_available,
        sum(case when is_any_email_setting_available = True and is_email_tech_available = True then 1 end) as email_available,
        sum(case when is_any_email_default_setting_available = True then 1 end) as email_default_settings_available,
        sum(case when marketing_email_received > 0 then 1 end) as email_marketing_received,
        sum(case when is_any_email_nondefault_setting_available = True then 1 end) as email_nondefault_settings_available,
        sum(case when rec_email_received > 0 then 1 end) as email_rec_received,
        sum(case when email_received > 0 then 1 end) as email_received,
        sum(case when is_any_email_setting_available = True then 1 end) as email_settings_available,
        sum(case when is_email_tech_available = True then 1 end) as email_tech_available,
        sum(case when is_any_messenger_setting_available = True and is_messenger_tech_available = True then 1 end) as messenger_available,
        sum(case when is_any_messenger_default_setting_available = True then 1 end) as messenger_default_settings_available,
        sum(case when marketing_messenger_received > 0 then 1 end) as messenger_marketing_received,
        sum(case when is_any_messenger_nondefault_setting_available = True then 1 end) as messenger_nondefault_settings_available,
        sum(case when rec_messenger_received > 0 then 1 end) as messenger_rec_received,
        sum(case when messenger_received > 0 then 1 end) as messenger_received,
        sum(case when is_any_messenger_setting_available = True then 1 end) as messenger_settings_available,
        sum(case when is_messenger_tech_available = True then 1 end) as messenger_tech_available,
        sum(case when is_any_nc_setting_available = True and is_nc_tech_available = True then 1 end) as nc_available,
        sum(case when marketing_nc_received > 0 then 1 end) as nc_marketing_received,
        sum(case when rec_nc_received > 0 then 1 end) as nc_rec_received,
        sum(case when nc_received > 0 then 1 end) as nc_received,
        sum(case when is_any_nc_setting_available = True then 1 end) as nc_settings_available,
        sum(case when is_nc_tech_available = True then 1 end) as nc_tech_available
    from notification_availability t
    group by user_id
) _
;
