create fact re_nd_buyer_stream as
select
    t.event_date::date as __date__,
    *
from dma.vo_re_nd_buyer_stream t
;

create metrics re_nd_buyer_stream as
select
    sum(case when eid in (3131, 6601) and node_type = 'banner' then 1 end) as catalog_jk_banner,
    sum(case when eid in (3131, 6601) then 1 end) as catalog_jk_entry_point,
    sum(case when eid = 5235 and catalog_jk_source = 'card_gallery' then 1 end) as catalog_jk_gallery_view_card,
    sum(case when eid = 5235 and catalog_jk_source = 'serp_snippet' then 1 end) as catalog_jk_gallery_view_serp,
    sum(case when eid in (3131, 6601) and node_type = 'catalog_jk' then 1 end) as catalog_jk_rubricator,
    sum(case when eid in (3131, 6601) and node_type = 'seo_links_click' then 1 end) as catalog_jk_seo_links_click,
    sum(case when eid in (3131, 6601) and node_type = 'serp' then 1 end) as catalog_jk_serp,
    sum(case when eid in (3131, 6601) and (node_type in ('vertical_main', 'vertical_main_featured', 'vertical_main_services')) then 1 end) as catalog_jk_vertical_main,
    sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_back_call_card_auction,
    sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_back_call_card_cpa,
    sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_back_call_card_cpa_not_auction,
    sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_back_call_card_not_cpa,
    sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_back_call_item_auction,
    sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_back_call_item_cpa,
    sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_back_call_item_cpa_not_auction,
    sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_back_call_item_not_cpa,
    sum(case when eid = 4476 then 1 end) as realty_dev_badge,
    sum(case when realty_development_flags & 2 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_auction,
    sum(case when realty_development_flags & 1 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_cpa,
    sum(case when realty_development_flags & 2 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_cpa_not_auction,
    sum(case when realty_development_flags & 1 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_not_cpa,
    sum(case when eid = 5237 and catalog_jk_source = 'card' then 1 end) as realty_dev_card_map_click,
    sum(case when (eid = 5236 and catalog_jk_source = 'catalogNDSource' and catalog_jk_action = 'add_items' or eid = 3460 and catalog_jk_attribute != -100 and catalog_jk_attribute is not null) then 1 end) as realty_dev_click_developer_item_serp,
    sum(case when eid = 3460 and (catalog_jk_attribute = -100 or catalog_jk_source = 'private_flats') then 1 end) as realty_dev_click_private_item_serp,
    sum(case when eid = 5281 then 1 end) as realty_dev_discount,
    sum(case when eid = 303 and item_flags & 4 > 0 then 1 end) as realty_dev_discount_item_c,
    sum(case when eid = 301 and item_flags & 4 > 0 then 1 end) as realty_dev_discount_item_iv,
    sum(case when realty_development_flags & 4 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_discount_jk_c,
    sum(case when eid = 3459 and realty_development_flags & 4 > 0 then 1 end) as realty_dev_discount_jk_iv,
    sum(case when eid = 5281 and catalog_jk_attribute = 1 then 1 end) as realty_dev_discount_link,
    sum(case when eid = 5281 and catalog_jk_attribute = 130 then 1 end) as realty_dev_discount_link2,
    sum(case when eid = 6546 then 1 end) as realty_dev_discount_swipe,
    sum(case when eid = 6532 then 1 end) as realty_dev_discount_viewport,
    sum(case when eid = 303 and item_flags & 8 > 0 then 1 end) as realty_dev_featured_item_c,
    sum(case when eid = 301 and item_flags & 8 > 0 then 1 end) as realty_dev_featured_item_iv,
    sum(case when realty_development_flags & 8 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_featured_jk_c,
    sum(case when eid = 3459 and realty_development_flags & 8 > 0 then 1 end) as realty_dev_featured_jk_iv,
    sum(case when eid = 4198 and from_page = 'item_contact_block' then 1 end) as realty_dev_item_back_call,
    sum(case when eid = 4198 and from_page = 'item_consultation_form' then 1 end) as realty_dev_item_back_call_consultation_form,
    sum(case when eid = 4198 and from_page = 'item_discounts' then 1 end) as realty_dev_item_back_call_discount,
    sum(case when eid = 303 then 1 end) as realty_dev_item_c,
    sum(case when eid = 303 and (phone_view_source in ('item_button', 'item_karusel')) then 1 end) as realty_dev_item_c_discount,
    sum(case when eid = 303 and phone_view_source = 'item_button' then 1 end) as realty_dev_item_c_discount_button,
    sum(case when eid = 303 and phone_view_source = 'item_karusel' then 1 end) as realty_dev_item_c_discount_carusel,
    sum(case when eid = 301 then 1 end) as realty_dev_item_iv,
    sum(case when eid = 303 and item_flags & 4 = 0 then 1 end) as realty_dev_not_discount_item_c,
    sum(case when eid = 301 and item_flags & 4 = 0 then 1 end) as realty_dev_not_discount_item_iv,
    sum(case when realty_development_flags & 4 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_not_discount_jk_c,
    sum(case when eid = 3459 and realty_development_flags & 4 = 0 then 1 end) as realty_dev_not_discount_jk_iv,
    sum(case when eid = 303 and item_flags & 8 = 0 then 1 end) as realty_dev_not_featured_item_c,
    sum(case when eid = 301 and item_flags & 8 = 0 then 1 end) as realty_dev_not_featured_item_iv,
    sum(case when realty_development_flags & 8 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_not_featured_jk_c,
    sum(case when eid = 3459 and realty_development_flags & 8 = 0 then 1 end) as realty_dev_not_featured_jk_iv,
    sum(case when eid = 3461 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_ph_auction,
    sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and item_id_not_null = 0 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_ph_card_auction,
    sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_ph_card_cpa,
    sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and item_id_not_null = 0 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_ph_card_cpa_not_auction,
    sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and item_id_not_null = 0 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_ph_card_not_cpa,
    sum(case when eid = 3461 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_ph_cpa,
    sum(case when eid = 3461 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_ph_cpa_not_auction,
    sum(case when eid = 3461 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_ph_not_cpa,
    sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_ph_serp_auction,
    sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_ph_serp_cpa,
    sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_ph_serp_cpa_not_auction,
    sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_ph_serp_not_cpa,
    sum(case when eid = 3459 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_auction,
    sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_cat_jk_serp_auction,
    sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_cat_jk_serp_cpa,
    sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_cat_jk_serp_cpa_not_auction,
    sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_cat_jk_serp_not_cpa,
    sum(case when eid = 3459 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_cpa,
    sum(case when eid = 3459 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_cpa_not_auction,
    sum(case when eid = 3459 and from_page in ('item_jk_button', 'item_jk_name') and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_item_auction,
    sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_item_button_auction,
    sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_item_button_cpa,
    sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_item_button_cpa_not_auction,
    sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_item_button_not_cpa,
    sum(case when eid = 3459 and realty_development_flags & 1 > 0 and (from_page in ('item_jk_button', 'item_jk_name')) then 1 end) as realty_dev_views_item_cpa,
    sum(case when eid = 3459 and from_page in ('item_jk_button', 'item_jk_name') and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_item_cpa_not_auction,
    sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_item_name_auction,
    sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_item_name_cpa,
    sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_item_name_cpa_not_auction,
    sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_item_name_not_cpa,
    sum(case when eid = 3459 and from_page in ('item_jk_button', 'item_jk_name') and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_item_not_cpa,
    sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_map_auction,
    sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_map_cpa,
    sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_map_cpa_not_auction,
    sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_map_not_cpa,
    sum(case when eid = 3459 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_not_cpa,
    sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_rec_auction,
    sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_rec_cpa,
    sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_rec_cpa_not_auction,
    sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_rec_not_cpa,
    sum(case when eid = 303 and item_flags & 2 > 0 then 1 end) as realty_item_c_auction,
    sum(case when eid = 303 and item_flags & 2 = 0 then 1 end) as realty_item_c_cpa_not_auction,
    sum(case when eid = 301 and item_flags & 2 > 0 then 1 end) as realty_item_views_auction,
    sum(case when eid = 301 and item_flags & 2 = 0 then 1 end) as realty_item_views_cpa_not_auction
from re_nd_buyer_stream t
;

create metrics re_nd_buyer_stream_cookie as
select
    sum(case when catalog_jk_entry_point > 0 then 1 end) as user_catalog_jk_entry_point,
    sum(case when realty_dev_discount_item_c > 0 then 1 end) as user_realty_dev_discount_item_c,
    sum(case when realty_dev_discount_item_iv > 0 then 1 end) as user_realty_dev_discount_item_iv,
    sum(case when realty_dev_discount_jk_c > 0 then 1 end) as user_realty_dev_discount_jk_c,
    sum(case when realty_dev_discount_jk_iv > 0 then 1 end) as user_realty_dev_discount_jk_iv,
    sum(case when realty_dev_featured_item_c > 0 then 1 end) as user_realty_dev_featured_item_c,
    sum(case when realty_dev_featured_item_iv > 0 then 1 end) as user_realty_dev_featured_item_iv,
    sum(case when realty_dev_featured_jk_c > 0 then 1 end) as user_realty_dev_featured_jk_c,
    sum(case when realty_dev_featured_jk_iv > 0 then 1 end) as user_realty_dev_featured_jk_iv,
    sum(case when realty_dev_item_back_call > 0 then 1 end) as user_realty_dev_item_back_call,
    sum(case when realty_dev_item_back_call_consultation_form > 0 then 1 end) as user_realty_dev_item_back_call_consultation_form,
    sum(case when realty_dev_item_back_call_discount > 0 then 1 end) as user_realty_dev_item_back_call_discount,
    sum(case when realty_dev_item_c > 0 then 1 end) as user_realty_dev_item_c,
    sum(case when realty_dev_item_c_discount > 0 then 1 end) as user_realty_dev_item_c_discount,
    sum(case when realty_dev_item_c_discount_button > 0 then 1 end) as user_realty_dev_item_c_discount_button,
    sum(case when realty_dev_item_c_discount_carusel > 0 then 1 end) as user_realty_dev_item_c_discount_carusel,
    sum(case when realty_dev_item_iv > 0 then 1 end) as user_realty_dev_item_iv,
    sum(case when realty_dev_not_discount_item_c > 0 then 1 end) as user_realty_dev_not_discount_item_c,
    sum(case when realty_dev_not_discount_item_iv > 0 then 1 end) as user_realty_dev_not_discount_item_iv,
    sum(case when realty_dev_not_discount_jk_c > 0 then 1 end) as user_realty_dev_not_discount_jk_c,
    sum(case when realty_dev_not_discount_jk_iv > 0 then 1 end) as user_realty_dev_not_discount_jk_iv,
    sum(case when realty_dev_not_featured_item_c > 0 then 1 end) as user_realty_dev_not_featured_item_c,
    sum(case when realty_dev_not_featured_item_iv > 0 then 1 end) as user_realty_dev_not_featured_item_iv,
    sum(case when realty_dev_not_featured_jk_c > 0 then 1 end) as user_realty_dev_not_featured_jk_c,
    sum(case when realty_dev_not_featured_jk_iv > 0 then 1 end) as user_realty_dev_not_featured_jk_iv,
    sum(case when catalog_jk_banner > 0 then 1 end) as users_catalog_jk_banner,
    sum(case when catalog_jk_gallery_view_card > 0 then 1 end) as users_catalog_jk_gallery_view_card,
    sum(case when catalog_jk_gallery_view_serp > 0 then 1 end) as users_catalog_jk_gallery_view_serp,
    sum(case when catalog_jk_rubricator > 0 then 1 end) as users_catalog_jk_rubricator,
    sum(case when catalog_jk_seo_links_click > 0 then 1 end) as users_catalog_jk_seo_links_click,
    sum(case when catalog_jk_serp > 0 then 1 end) as users_catalog_jk_serp,
    sum(case when catalog_jk_vertical_main > 0 then 1 end) as users_catalog_jk_vertical_main,
    sum(case when realty_dev_back_call_card_auction > 0 then 1 end) as users_realty_dev_back_call_card_auction,
    sum(case when realty_dev_back_call_card_cpa > 0 then 1 end) as users_realty_dev_back_call_card_cpa,
    sum(case when realty_dev_back_call_card_cpa_not_auction > 0 then 1 end) as users_realty_dev_back_call_card_cpa_not_auction,
    sum(case when realty_dev_back_call_card_not_cpa > 0 then 1 end) as users_realty_dev_back_call_card_not_cpa,
    sum(case when realty_dev_back_call_item_auction > 0 then 1 end) as users_realty_dev_back_call_item_auction,
    sum(case when realty_dev_back_call_item_cpa > 0 then 1 end) as users_realty_dev_back_call_item_cpa,
    sum(case when realty_dev_back_call_item_cpa_not_auction > 0 then 1 end) as users_realty_dev_back_call_item_cpa_not_auction,
    sum(case when realty_dev_back_call_item_not_cpa > 0 then 1 end) as users_realty_dev_back_call_item_not_cpa,
    sum(case when realty_dev_badge > 0 then 1 end) as users_realty_dev_badge,
    sum(case when realty_dev_c_auction > 0 then 1 end) as users_realty_dev_c_auction,
    sum(case when realty_dev_c_cpa > 0 then 1 end) as users_realty_dev_c_cpa,
    sum(case when realty_dev_c_cpa_not_auction > 0 then 1 end) as users_realty_dev_c_cpa_not_auction,
    sum(case when realty_dev_c_not_cpa > 0 then 1 end) as users_realty_dev_c_not_cpa,
    sum(case when realty_dev_card_map_click > 0 then 1 end) as users_realty_dev_card_map_click,
    sum(case when realty_dev_click_developer_item_serp > 0 then 1 end) as users_realty_dev_click_developer_item_serp,
    sum(case when realty_dev_click_private_item_serp > 0 then 1 end) as users_realty_dev_click_private_item_serp,
    sum(case when realty_dev_discount > 0 then 1 end) as users_realty_dev_discount,
    sum(case when realty_dev_discount_swipe > 0 then 1 end) as users_realty_dev_discount_swipe,
    sum(case when realty_dev_discount_viewport > 0 then 1 end) as users_realty_dev_discount_viewport,
    sum(case when realty_dev_ph_auction > 0 then 1 end) as users_realty_dev_ph_auction,
    sum(case when realty_dev_ph_card_auction > 0 then 1 end) as users_realty_dev_ph_card_auction,
    sum(case when realty_dev_ph_card_cpa > 0 then 1 end) as users_realty_dev_ph_card_cpa,
    sum(case when realty_dev_ph_card_cpa_not_auction > 0 then 1 end) as users_realty_dev_ph_card_cpa_not_auction,
    sum(case when realty_dev_ph_card_not_cpa > 0 then 1 end) as users_realty_dev_ph_card_not_cpa,
    sum(case when realty_dev_ph_cpa > 0 then 1 end) as users_realty_dev_ph_cpa,
    sum(case when realty_dev_ph_cpa_not_auction > 0 then 1 end) as users_realty_dev_ph_cpa_not_auction,
    sum(case when realty_dev_ph_not_cpa > 0 then 1 end) as users_realty_dev_ph_not_cpa,
    sum(case when realty_dev_ph_serp_auction > 0 then 1 end) as users_realty_dev_ph_serp_auction,
    sum(case when realty_dev_ph_serp_cpa > 0 then 1 end) as users_realty_dev_ph_serp_cpa,
    sum(case when realty_dev_ph_serp_cpa_not_auction > 0 then 1 end) as users_realty_dev_ph_serp_cpa_not_auction,
    sum(case when realty_dev_ph_serp_not_cpa > 0 then 1 end) as users_realty_dev_ph_serp_not_cpa,
    sum(case when realty_dev_views_auction > 0 then 1 end) as users_realty_dev_views_auction,
    sum(case when realty_dev_views_cat_jk_serp_auction > 0 then 1 end) as users_realty_dev_views_cat_jk_serp_auction,
    sum(case when realty_dev_views_cat_jk_serp_cpa > 0 then 1 end) as users_realty_dev_views_cat_jk_serp_cpa,
    sum(case when realty_dev_views_cat_jk_serp_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_cat_jk_serp_cpa_not_auction,
    sum(case when realty_dev_views_cat_jk_serp_not_cpa > 0 then 1 end) as users_realty_dev_views_cat_jk_serp_not_cpa,
    sum(case when realty_dev_views_cpa > 0 then 1 end) as users_realty_dev_views_cpa,
    sum(case when realty_dev_views_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_cpa_not_auction,
    sum(case when realty_dev_views_item_auction > 0 then 1 end) as users_realty_dev_views_item_auction,
    sum(case when realty_dev_views_item_button_auction > 0 then 1 end) as users_realty_dev_views_item_button_auction,
    sum(case when realty_dev_views_item_button_cpa > 0 then 1 end) as users_realty_dev_views_item_button_cpa,
    sum(case when realty_dev_views_item_button_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_item_button_cpa_not_auction,
    sum(case when realty_dev_views_item_button_not_cpa > 0 then 1 end) as users_realty_dev_views_item_button_not_cpa,
    sum(case when realty_dev_views_item_cpa > 0 then 1 end) as users_realty_dev_views_item_cpa,
    sum(case when realty_dev_views_item_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_item_cpa_not_auction,
    sum(case when realty_dev_views_item_name_auction > 0 then 1 end) as users_realty_dev_views_item_name_auction,
    sum(case when realty_dev_views_item_name_cpa > 0 then 1 end) as users_realty_dev_views_item_name_cpa,
    sum(case when realty_dev_views_item_name_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_item_name_cpa_not_auction,
    sum(case when realty_dev_views_item_name_not_cpa > 0 then 1 end) as users_realty_dev_views_item_name_not_cpa,
    sum(case when realty_dev_views_item_not_cpa > 0 then 1 end) as users_realty_dev_views_item_not_cpa,
    sum(case when realty_dev_views_map_auction > 0 then 1 end) as users_realty_dev_views_map_auction,
    sum(case when realty_dev_views_map_cpa > 0 then 1 end) as users_realty_dev_views_map_cpa,
    sum(case when realty_dev_views_map_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_map_cpa_not_auction,
    sum(case when realty_dev_views_map_not_cpa > 0 then 1 end) as users_realty_dev_views_map_not_cpa,
    sum(case when realty_dev_views_not_cpa > 0 then 1 end) as users_realty_dev_views_not_cpa,
    sum(case when realty_dev_views_rec_auction > 0 then 1 end) as users_realty_dev_views_rec_auction,
    sum(case when realty_dev_views_rec_cpa > 0 then 1 end) as users_realty_dev_views_rec_cpa,
    sum(case when realty_dev_views_rec_cpa_not_auction > 0 then 1 end) as users_realty_dev_views_rec_cpa_not_auction,
    sum(case when realty_dev_views_rec_not_cpa > 0 then 1 end) as users_realty_dev_views_rec_not_cpa,
    sum(case when realty_item_c_auction > 0 then 1 end) as users_realty_item_c_auction,
    sum(case when realty_item_c_cpa_not_auction > 0 then 1 end) as users_realty_item_c_cpa_not_auction,
    sum(case when realty_item_views_auction > 0 then 1 end) as users_realty_item_views_auction,
    sum(case when realty_item_views_cpa_not_auction > 0 then 1 end) as users_realty_item_views_cpa_not_auction
from (
    select
        cookie_id,
        sum(case when eid in (3131, 6601) and node_type = 'banner' then 1 end) as catalog_jk_banner,
        sum(case when eid in (3131, 6601) then 1 end) as catalog_jk_entry_point,
        sum(case when eid = 5235 and catalog_jk_source = 'card_gallery' then 1 end) as catalog_jk_gallery_view_card,
        sum(case when eid = 5235 and catalog_jk_source = 'serp_snippet' then 1 end) as catalog_jk_gallery_view_serp,
        sum(case when eid in (3131, 6601) and node_type = 'catalog_jk' then 1 end) as catalog_jk_rubricator,
        sum(case when eid in (3131, 6601) and node_type = 'seo_links_click' then 1 end) as catalog_jk_seo_links_click,
        sum(case when eid in (3131, 6601) and node_type = 'serp' then 1 end) as catalog_jk_serp,
        sum(case when eid in (3131, 6601) and (node_type in ('vertical_main', 'vertical_main_featured', 'vertical_main_services')) then 1 end) as catalog_jk_vertical_main,
        sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_back_call_card_auction,
        sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_back_call_card_cpa,
        sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_back_call_card_cpa_not_auction,
        sum(case when eid = 4198 and item_id_not_null = 0 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_back_call_card_not_cpa,
        sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_back_call_item_auction,
        sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_back_call_item_cpa,
        sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_back_call_item_cpa_not_auction,
        sum(case when eid = 4198 and item_id_not_null = 1 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_back_call_item_not_cpa,
        sum(case when eid = 4476 then 1 end) as realty_dev_badge,
        sum(case when realty_development_flags & 2 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_auction,
        sum(case when realty_development_flags & 1 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_cpa,
        sum(case when realty_development_flags & 2 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_cpa_not_auction,
        sum(case when realty_development_flags & 1 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_c_not_cpa,
        sum(case when eid = 5237 and catalog_jk_source = 'card' then 1 end) as realty_dev_card_map_click,
        sum(case when (eid = 5236 and catalog_jk_source = 'catalogNDSource' and catalog_jk_action = 'add_items' or eid = 3460 and catalog_jk_attribute != -100 and catalog_jk_attribute is not null) then 1 end) as realty_dev_click_developer_item_serp,
        sum(case when eid = 3460 and (catalog_jk_attribute = -100 or catalog_jk_source = 'private_flats') then 1 end) as realty_dev_click_private_item_serp,
        sum(case when eid = 5281 then 1 end) as realty_dev_discount,
        sum(case when eid = 303 and item_flags & 4 > 0 then 1 end) as realty_dev_discount_item_c,
        sum(case when eid = 301 and item_flags & 4 > 0 then 1 end) as realty_dev_discount_item_iv,
        sum(case when realty_development_flags & 4 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_discount_jk_c,
        sum(case when eid = 3459 and realty_development_flags & 4 > 0 then 1 end) as realty_dev_discount_jk_iv,
        sum(case when eid = 6546 then 1 end) as realty_dev_discount_swipe,
        sum(case when eid = 6532 then 1 end) as realty_dev_discount_viewport,
        sum(case when eid = 303 and item_flags & 8 > 0 then 1 end) as realty_dev_featured_item_c,
        sum(case when eid = 301 and item_flags & 8 > 0 then 1 end) as realty_dev_featured_item_iv,
        sum(case when realty_development_flags & 8 > 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_featured_jk_c,
        sum(case when eid = 3459 and realty_development_flags & 8 > 0 then 1 end) as realty_dev_featured_jk_iv,
        sum(case when eid = 4198 and from_page = 'item_contact_block' then 1 end) as realty_dev_item_back_call,
        sum(case when eid = 4198 and from_page = 'item_consultation_form' then 1 end) as realty_dev_item_back_call_consultation_form,
        sum(case when eid = 4198 and from_page = 'item_discounts' then 1 end) as realty_dev_item_back_call_discount,
        sum(case when eid = 303 then 1 end) as realty_dev_item_c,
        sum(case when eid = 303 and (phone_view_source in ('item_button', 'item_karusel')) then 1 end) as realty_dev_item_c_discount,
        sum(case when eid = 303 and phone_view_source = 'item_button' then 1 end) as realty_dev_item_c_discount_button,
        sum(case when eid = 303 and phone_view_source = 'item_karusel' then 1 end) as realty_dev_item_c_discount_carusel,
        sum(case when eid = 301 then 1 end) as realty_dev_item_iv,
        sum(case when eid = 303 and item_flags & 4 = 0 then 1 end) as realty_dev_not_discount_item_c,
        sum(case when eid = 301 and item_flags & 4 = 0 then 1 end) as realty_dev_not_discount_item_iv,
        sum(case when realty_development_flags & 4 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_not_discount_jk_c,
        sum(case when eid = 3459 and realty_development_flags & 4 = 0 then 1 end) as realty_dev_not_discount_jk_iv,
        sum(case when eid = 303 and item_flags & 8 = 0 then 1 end) as realty_dev_not_featured_item_c,
        sum(case when eid = 301 and item_flags & 8 = 0 then 1 end) as realty_dev_not_featured_item_iv,
        sum(case when realty_development_flags & 8 = 0 and (eid = 3461 or eid = 4198 and item_id_not_null = 0) then 1 end) as realty_dev_not_featured_jk_c,
        sum(case when eid = 3459 and realty_development_flags & 8 = 0 then 1 end) as realty_dev_not_featured_jk_iv,
        sum(case when eid = 3461 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_ph_auction,
        sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and item_id_not_null = 0 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_ph_card_auction,
        sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_ph_card_cpa,
        sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and item_id_not_null = 0 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_ph_card_cpa_not_auction,
        sum(case when eid = 3461 and catalog_jk_source != 'serp_snippet' and item_id_not_null = 0 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_ph_card_not_cpa,
        sum(case when eid = 3461 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_ph_cpa,
        sum(case when eid = 3461 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_ph_cpa_not_auction,
        sum(case when eid = 3461 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_ph_not_cpa,
        sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_ph_serp_auction,
        sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_ph_serp_cpa,
        sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_ph_serp_cpa_not_auction,
        sum(case when eid = 3461 and catalog_jk_source = 'serp_snippet' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_ph_serp_not_cpa,
        sum(case when eid = 3459 and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_auction,
        sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_cat_jk_serp_auction,
        sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_cat_jk_serp_cpa,
        sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_cat_jk_serp_cpa_not_auction,
        sum(case when eid = 3459 and from_page = 'catalog_jk_serp' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_cat_jk_serp_not_cpa,
        sum(case when eid = 3459 and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_cpa,
        sum(case when eid = 3459 and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_cpa_not_auction,
        sum(case when eid = 3459 and from_page in ('item_jk_button', 'item_jk_name') and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_item_auction,
        sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_item_button_auction,
        sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_item_button_cpa,
        sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_item_button_cpa_not_auction,
        sum(case when eid = 3459 and from_page = 'item_jk_button' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_item_button_not_cpa,
        sum(case when eid = 3459 and realty_development_flags & 1 > 0 and (from_page in ('item_jk_button', 'item_jk_name')) then 1 end) as realty_dev_views_item_cpa,
        sum(case when eid = 3459 and from_page in ('item_jk_button', 'item_jk_name') and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_item_cpa_not_auction,
        sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_item_name_auction,
        sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_item_name_cpa,
        sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_item_name_cpa_not_auction,
        sum(case when eid = 3459 and from_page = 'item_jk_name' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_item_name_not_cpa,
        sum(case when eid = 3459 and from_page in ('item_jk_button', 'item_jk_name') and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_item_not_cpa,
        sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_map_auction,
        sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_map_cpa,
        sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_map_cpa_not_auction,
        sum(case when eid = 3459 and from_page = 'map' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_map_not_cpa,
        sum(case when eid = 3459 and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_not_cpa,
        sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 2 > 0 then 1 end) as realty_dev_views_rec_auction,
        sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 1 > 0 then 1 end) as realty_dev_views_rec_cpa,
        sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 2 = 0 then 1 end) as realty_dev_views_rec_cpa_not_auction,
        sum(case when eid = 3459 and from_page = 'jk_card_rec' and realty_development_flags & 1 = 0 then 1 end) as realty_dev_views_rec_not_cpa,
        sum(case when eid = 303 and item_flags & 2 > 0 then 1 end) as realty_item_c_auction,
        sum(case when eid = 303 and item_flags & 2 = 0 then 1 end) as realty_item_c_cpa_not_auction,
        sum(case when eid = 301 and item_flags & 2 > 0 then 1 end) as realty_item_views_auction,
        sum(case when eid = 301 and item_flags & 2 = 0 then 1 end) as realty_item_views_cpa_not_auction
    from re_nd_buyer_stream t
    group by cookie_id
) _
;
