create fact clickstream as
select
    t.event_date::date as __date__,
    t.cookie_id as cookie,
    t.cookie_id,
    t.eid,
    t.event_count,
    t.event_date,
    t.has_error,
    t.has_item,
    t.location_id,
    t.microcat_id,
    t.user_id
from dma.vo_clickstream_new t
;

create metrics clickstream as
select
    sum(case when eid = 305 then event_count end) as abuses,
    sum(case when eid = 3197 then event_count end) as address_item_page_clicks,
    sum(case when eid = 2838 then event_count end) as allcategories_tap,
    sum(case when eid = 2744 then event_count end) as app_stat_button_click,
    sum(case when eid = 2148 then event_count end) as app_vas_button_click,
    sum(case when eid = 4355 then event_count end) as auto_owner_foto_start,
    sum(case when eid = 4405 then event_count end) as bargain_offer_price,
    sum(case when eid = 299 then event_count end) as call_phones,
    sum(case when eid = 3380 then event_count end) as calls_dialogues,
    sum(case when eid = 4670 then event_count end) as card_model,
    sum(case when eid = 4748 then event_count end) as charity_bottom_sheet_show,
    sum(case when eid = 4741 then event_count end) as charity_landing_show,
    sum(case when eid = 854 then event_count end) as chat_reads,
    sum(case when eid = 853 then event_count end) as chats_deleted,
    sum(case when eid = 2782 then event_count end) as click_back,
    sum(case when eid = 4404 then event_count end) as click_torg_btn,
    sum(case when eid = 3414 then event_count end) as contacts_history_open_in_ratings,
    sum(case when eid = 2967 then event_count end) as created_reviews_list_open,
    sum(case when eid = 3047 then event_count end) as domoteka_preview_clicks,
    sum(case when eid = 3052 then event_count end) as domoteka_report_payment,
    sum(case when eid = 3051 then event_count end) as domoteka_report_requests,
    sum(case when eid = 3246 then event_count end) as favouriteseller_notifications_offs,
    sum(case when eid = 3245 then event_count end) as favouriteseller_notifications_ons,
    sum(case when eid = 3463 then event_count end) as favouriteseller_page_opens,
    sum(case when eid = 2783 then event_count end) as filters_opening,
    sum(case when eid = 3232 then event_count end) as filters_screen_shows,
    sum(case when eid = 2090 then event_count end) as forgot_password_count,
    sum(case when eid = 4434 then event_count end) as fraud_modal_window_show,
    sum(case when eid = 3227 then event_count end) as fullscreen_photo_galeree_close,
    sum(case when eid = 3192 then event_count end) as fullscreen_photo_galeree_open,
    sum(case when eid = 5069 then event_count end) as iac_is_available_on_item_add,
    sum(case when eid = 4159 then event_count end) as inline_filter_click,
    sum(case when eid = 4196 then event_count end) as inline_filter_value,
    sum(case when eid = 2924 then event_count end) as item_add_reactivation_start,
    sum(case when eid = 333 then event_count end) as item_addfinish,
    sum(case when eid = 2331 then event_count end) as item_close_popup_open,
    sum(case when eid = 3848 then event_count end) as item_hide,
    sum(case when eid = 310 and has_item = False and location_id is null and microcat_id is null then event_count end) as items_add_started,
    sum(case when eid = 3949 then event_count end) as items_added,
    sum(case when eid = 4082 then event_count end) as map_interaction_on_item,
    sum(case when eid = 858 then event_count end) as message_reads,
    sum(case when eid = 4413 then event_count end) as mic_popup_post_item_add,
    sum(case when eid = 4414 then event_count end) as mic_popup_post_item_add_click,
    sum(case when eid = 5184 then event_count end) as model_card_goods,
    sum(case when eid = 4198 and has_item = True then event_count end) as nd_banner_successful_dis_for_back_call_item,
    sum(case when eid = 4198 and has_item = False then event_count end) as nd_banner_successful_dis_for_back_call_jk,
    sum(case when eid = 4198 then event_count end) as nd_banner_successful_dispatch_for_back_call,
    sum(case when eid = 4219 then event_count end) as nd_click_request_call,
    sum(case when eid = 4197 then event_count end) as nd_click_submit_application_for_back_call,
    sum(case when eid = 2330 then event_count end) as open_app,
    sum(case when eid = 4520 then event_count end) as orders_page_buy,
    sum(case when eid = 4513 then event_count end) as orders_page_sell,
    sum(case when eid = 4512 then event_count end) as orders_page_views,
    sum(case when eid = 212 then event_count end) as password_restore_request_attempts,
    sum(case when eid = 212 and has_error = True then event_count end) as password_restore_request_errors,
    sum(case when eid = 212 and has_error = False then event_count end) as password_restore_requests,
    sum(case when eid = 3191 then event_count end) as photo_zoom_on_item_page,
    sum(case when eid = 2755 then event_count end) as received_reviews_list_open,
    sum(case when eid = 2756 then event_count end) as review_add_open_page,
    sum(case when eid = 3007 then event_count end) as review_delete,
    sum(case when eid = 2754 then event_count end) as reviews_list_open,
    sum(case when eid = 3006 then event_count end) as saved_searches_email_item_clicks,
    sum(case when eid = 3000 then event_count end) as saved_searches_list_views,
    sum(case when eid = 3004 then event_count end) as saved_searches_notifications_offs,
    sum(case when eid = 3003 then event_count end) as saved_searches_notifications_ons,
    sum(case when eid = 3002 then event_count end) as saved_searches_removals,
    sum(case when eid = 3001 then event_count end) as saved_searches_views,
    sum(case when eid = 2119 then event_count end) as seller_own_item_views,
    sum(case when eid = 230 then event_count end) as seller_profile_views,
    sum(case when eid = 210 and has_error = False then event_count end) as sign_in_count,
    sum(case when eid = 210 and has_error = True then event_count end) as sign_in_errors,
    sum(case when eid = 4203 then event_count end) as stories_list_clicks,
    sum(case when eid = 4310 then event_count end) as stories_list_shows,
    sum(case when eid = 4297 then event_count end) as story_clicks,
    sum(case when eid = 4233 then event_count end) as story_shows,
    sum(case when eid = 2700 then event_count end) as str_inventory_edit_button_click
from clickstream t
;

create metrics clickstream_cookie as
select
    sum(case when orders_page_buy > 0 then 1 end) as orders_page_buy_users,
    sum(case when orders_page_sell > 0 then 1 end) as orders_page_sell_users,
    sum(case when orders_page_views > 0 then 1 end) as orders_page_views_users,
    sum(case when items_added > 0 then 1 end) as sellers_daily,
    sum(case when seller_own_item_views > 0 then 1 end) as sellers_own_item_viewed,
    sum(case when seller_profile_views > 0 then 1 end) as sellers_profile_viewed,
    sum(case when address_item_page_clicks > 0 then 1 end) as user_address_item_page_clicks,
    sum(case when bargain_offer_price > 0 then 1 end) as user_bargain_offer_price,
    sum(case when card_model > 0 then 1 end) as user_card_model,
    sum(case when click_torg_btn > 0 then 1 end) as user_click_torg_btn,
    sum(case when created_reviews_list_open > 0 then 1 end) as user_created_reviews_list_open,
    sum(case when domoteka_preview_clicks > 0 then 1 end) as user_domoteka_preview_clicks,
    sum(case when domoteka_report_payment > 0 then 1 end) as user_domoteka_report_payment,
    sum(case when domoteka_report_requests > 0 then 1 end) as user_domoteka_report_requests,
    sum(case when filters_screen_shows > 0 then 1 end) as user_filters_screen_shows,
    sum(case when inline_filter_click > 0 then 1 end) as user_inline_filter_click,
    sum(case when inline_filter_value > 0 then 1 end) as user_inline_filter_value,
    sum(case when map_interaction_on_item > 0 then 1 end) as user_map_interaction_on_item,
    sum(case when model_card_goods > 0 then 1 end) as user_model_card_goods,
    sum(case when nd_banner_successful_dis_for_back_call_item > 0 then 1 end) as user_nd_banner_successful_dis_for_back_call_item,
    sum(case when nd_banner_successful_dis_for_back_call_jk > 0 then 1 end) as user_nd_banner_successful_dis_for_back_call_jk,
    sum(case when nd_banner_successful_dispatch_for_back_call > 0 then 1 end) as user_nd_banner_successful_dispatch_for_back_call,
    sum(case when nd_click_request_call > 0 then 1 end) as user_nd_click_request_call,
    sum(case when nd_click_submit_application_for_back_call > 0 then 1 end) as user_nd_click_submit_application_for_back_call,
    sum(case when password_restore_requests > 0 then 1 end) as user_password_restore_request,
    sum(case when password_restore_request_attempts > 0 then 1 end) as user_password_restore_request_attempt,
    sum(case when received_reviews_list_open > 0 then 1 end) as user_received_reviews_list_open,
    sum(case when review_add_open_page > 0 then 1 end) as user_review_add_open_page,
    sum(case when review_delete > 0 then 1 end) as user_review_delete,
    sum(case when reviews_list_open > 0 then 1 end) as user_reviews_list_open,
    sum(case when stories_list_clicks > 0 then 1 end) as user_stories_list_clicks,
    sum(case when stories_list_shows > 0 then 1 end) as user_stories_list_shows,
    sum(case when story_clicks > 0 then 1 end) as user_story_clicks,
    sum(case when story_shows > 0 then 1 end) as user_story_shows,
    sum(case when favouriteseller_notifications_offs > 0 then 1 end) as users_favouriteseller_notifications_off,
    sum(case when favouriteseller_notifications_ons > 0 then 1 end) as users_favouriteseller_notifications_on,
    sum(case when favouriteseller_page_opens > 0 then 1 end) as users_favouriteseller_page_open,
    sum(case when items_add_started > 0 then 1 end) as users_item_add_started,
    sum(case when item_hide > 0 then 1 end) as users_item_hide_daily,
    sum(case when call_phones > 0 then 1 end) as users_phone_calls,
    sum(case when saved_searches_email_item_clicks > 0 then 1 end) as users_saved_searches_email_item_click,
    sum(case when saved_searches_list_views > 0 then 1 end) as users_saved_searches_list_view,
    sum(case when saved_searches_notifications_offs > 0 then 1 end) as users_saved_searches_notifications_off,
    sum(case when saved_searches_notifications_ons > 0 then 1 end) as users_saved_searches_notifications_on,
    sum(case when saved_searches_removals > 0 then 1 end) as users_saved_searches_removed,
    sum(case when saved_searches_views > 0 then 1 end) as users_saved_searches_view
from (
    select
        cookie_id, cookie,
        sum(case when eid = 3197 then event_count end) as address_item_page_clicks,
        sum(case when eid = 4405 then event_count end) as bargain_offer_price,
        sum(case when eid = 299 then event_count end) as call_phones,
        sum(case when eid = 4670 then event_count end) as card_model,
        sum(case when eid = 4404 then event_count end) as click_torg_btn,
        sum(case when eid = 2967 then event_count end) as created_reviews_list_open,
        sum(case when eid = 3047 then event_count end) as domoteka_preview_clicks,
        sum(case when eid = 3052 then event_count end) as domoteka_report_payment,
        sum(case when eid = 3051 then event_count end) as domoteka_report_requests,
        sum(case when eid = 3246 then event_count end) as favouriteseller_notifications_offs,
        sum(case when eid = 3245 then event_count end) as favouriteseller_notifications_ons,
        sum(case when eid = 3463 then event_count end) as favouriteseller_page_opens,
        sum(case when eid = 3232 then event_count end) as filters_screen_shows,
        sum(case when eid = 4159 then event_count end) as inline_filter_click,
        sum(case when eid = 4196 then event_count end) as inline_filter_value,
        sum(case when eid = 3848 then event_count end) as item_hide,
        sum(case when eid = 310 and has_item = False and location_id is null and microcat_id is null then event_count end) as items_add_started,
        sum(case when eid = 3949 then event_count end) as items_added,
        sum(case when eid = 4082 then event_count end) as map_interaction_on_item,
        sum(case when eid = 5184 then event_count end) as model_card_goods,
        sum(case when eid = 4198 and has_item = True then event_count end) as nd_banner_successful_dis_for_back_call_item,
        sum(case when eid = 4198 and has_item = False then event_count end) as nd_banner_successful_dis_for_back_call_jk,
        sum(case when eid = 4198 then event_count end) as nd_banner_successful_dispatch_for_back_call,
        sum(case when eid = 4219 then event_count end) as nd_click_request_call,
        sum(case when eid = 4197 then event_count end) as nd_click_submit_application_for_back_call,
        sum(case when eid = 4520 then event_count end) as orders_page_buy,
        sum(case when eid = 4513 then event_count end) as orders_page_sell,
        sum(case when eid = 4512 then event_count end) as orders_page_views,
        sum(case when eid = 212 then event_count end) as password_restore_request_attempts,
        sum(case when eid = 212 and has_error = False then event_count end) as password_restore_requests,
        sum(case when eid = 2755 then event_count end) as received_reviews_list_open,
        sum(case when eid = 2756 then event_count end) as review_add_open_page,
        sum(case when eid = 3007 then event_count end) as review_delete,
        sum(case when eid = 2754 then event_count end) as reviews_list_open,
        sum(case when eid = 3006 then event_count end) as saved_searches_email_item_clicks,
        sum(case when eid = 3000 then event_count end) as saved_searches_list_views,
        sum(case when eid = 3004 then event_count end) as saved_searches_notifications_offs,
        sum(case when eid = 3003 then event_count end) as saved_searches_notifications_ons,
        sum(case when eid = 3002 then event_count end) as saved_searches_removals,
        sum(case when eid = 3001 then event_count end) as saved_searches_views,
        sum(case when eid = 2119 then event_count end) as seller_own_item_views,
        sum(case when eid = 230 then event_count end) as seller_profile_views,
        sum(case when eid = 4203 then event_count end) as stories_list_clicks,
        sum(case when eid = 4310 then event_count end) as stories_list_shows,
        sum(case when eid = 4297 then event_count end) as story_clicks,
        sum(case when eid = 4233 then event_count end) as story_shows
    from clickstream t
    group by cookie_id, cookie
) _
;

create metrics clickstream_user_id as
select
    sum(case when app_stat_button_click > 0 then 1 end) as user_app_stat_button_click,
    sum(case when app_vas_button_click > 0 then 1 end) as user_app_vas_button_click,
    sum(case when auto_owner_foto_start > 0 then 1 end) as user_auto_owner_foto_start,
    sum(case when charity_bottom_sheet_show > 0 then 1 end) as user_charity_bottom_sheet_show,
    sum(case when charity_landing_show > 0 then 1 end) as user_charity_landing_show,
    sum(case when fraud_modal_window_show > 0 then 1 end) as user_fraud_modal_window_show,
    sum(case when iac_is_available_on_item_add > 0 then 1 end) as user_iac_is_available_on_item_add,
    sum(case when item_add_reactivation_start > 0 then 1 end) as user_item_add_reactivation_start,
    sum(case when item_addfinish > 0 then 1 end) as user_item_addfinish,
    sum(case when item_close_popup_open > 0 then 1 end) as user_item_close_popup_open,
    sum(case when mic_popup_post_item_add > 0 then 1 end) as user_mic_popup_post_item_add,
    sum(case when mic_popup_post_item_add_click > 0 then 1 end) as user_mic_popup_post_item_add_click,
    sum(case when str_inventory_edit_button_click > 0 then 1 end) as user_str_inventory_edit_button_click
from (
    select
        cookie_id, user_id,
        sum(case when eid = 2744 then event_count end) as app_stat_button_click,
        sum(case when eid = 2148 then event_count end) as app_vas_button_click,
        sum(case when eid = 4355 then event_count end) as auto_owner_foto_start,
        sum(case when eid = 4748 then event_count end) as charity_bottom_sheet_show,
        sum(case when eid = 4741 then event_count end) as charity_landing_show,
        sum(case when eid = 4434 then event_count end) as fraud_modal_window_show,
        sum(case when eid = 5069 then event_count end) as iac_is_available_on_item_add,
        sum(case when eid = 2924 then event_count end) as item_add_reactivation_start,
        sum(case when eid = 333 then event_count end) as item_addfinish,
        sum(case when eid = 2331 then event_count end) as item_close_popup_open,
        sum(case when eid = 4413 then event_count end) as mic_popup_post_item_add,
        sum(case when eid = 4414 then event_count end) as mic_popup_post_item_add_click,
        sum(case when eid = 2700 then event_count end) as str_inventory_edit_button_click
    from clickstream t
    group by cookie_id, user_id
) _
;
