create fact geo_loc_change as
select
    t.event_date as __date__,
    t.category_id,
    t.changing_geo_type,
    t.changing_quality_type,
    t.close_by,
    t.cookie_id as cookie,
    t.cookie_id,
    t.eid,
    t.event_date,
    t.events_count,
    t.location_id,
    t.location_level_id,
    t.open_from,
    t.open_from_id,
    t.prev_location_id,
    t.prev_location_level_id,
    t.session_no as session,
    t.subcategory_id,
    t.time_span,
    t.tooltip_close_type
from dma.vo_geo_loc_change t
;

create metrics geo_loc_change as
select
    sum(case when open_from = 'radius' and eid = 2918 and close_by > 0 then events_count end) as cnt_location_dialogue_savings_radius,
    sum(case when open_from = 'search' and eid = 2918 and close_by > 0 then events_count end) as cnt_location_dialogue_savings_s,
    sum(case when location_level_id in (4, 5, 6) and tooltip_close_type = 'accept' and eid = 2914 then events_count end) as cnt_tooltip_accepts_city,
    sum(case when location_level_id in (2, 3) and tooltip_close_type = 'accept' and eid = 2914 then events_count end) as cnt_tooltip_accepts_region,
    sum(case when location_level_id = 1 and tooltip_close_type = 'accept' and eid = 2914 then events_count end) as cnt_tooltip_accepts_russia,
    sum(case when location_level_id in (4, 5, 6) and tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as cnt_tooltip_not_accepts_city,
    sum(case when location_level_id in (2, 3) and tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as cnt_tooltip_not_accepts_region,
    sum(case when location_level_id = 1 and tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as cnt_tooltip_not_accepts_russia,
    sum(case when tooltip_close_type = 'accept' and eid = 2914 then events_count end) as default_loc_tooltip_accepts,
    sum(case when tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as default_loc_tooltip_declines,
    sum(case when eid = 2912 then events_count end) as default_loc_tooltip_shows,
    sum(case when location_level_id in (4, 5, 6) and eid = 2912 then events_count end) as default_loc_tooltip_shows_city,
    sum(case when location_level_id in (2, 3) and eid = 2912 then events_count end) as default_loc_tooltip_shows_region,
    sum(case when location_level_id = 1 and eid = 2912 then events_count end) as default_loc_tooltip_shows_russia,
    sum(case when tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts,
    sum(case when open_from_id = 'change' and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_change,
    sum(case when location_level_id in (4, 5, 6) and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_city,
    sum(case when location_level_id in (2, 3) and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_region,
    sum(case when open_from_id = 'regular' and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_regular,
    sum(case when location_level_id = 1 and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_russia,
    sum(case when eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers,
    sum(case when open_from_id = 'change' and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_change,
    sum(case when location_level_id in (4, 5, 6) and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_city,
    sum(case when location_level_id in (2, 3) and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_region,
    sum(case when open_from_id = 'regular' and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_regular,
    sum(case when location_level_id = 1 and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_russia,
    sum(case when eid = 4183 then events_count end) as laas_shows,
    sum(case when open_from_id = 'change' and eid = 4183 then events_count end) as laas_shows_change,
    sum(case when location_level_id in (4, 5, 6) and eid = 4183 then events_count end) as laas_shows_city,
    sum(case when location_level_id in (2, 3) and eid = 4183 then events_count end) as laas_shows_region,
    sum(case when open_from_id = 'regular' and eid = 4183 then events_count end) as laas_shows_regular,
    sum(case when location_level_id = 1 and eid = 4183 then events_count end) as laas_shows_russia,
    sum(case when changing_quality_type = 'bad' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_bad_chng,
    sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 and (changing_quality_type in ('bad', 'suspicious')) then events_count end) as loc_bad_susp_chng,
    sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng,
    sum(case when open_from = 'app settings' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_app_settings,
    sum(case when changing_quality_type = 'bad' and prev_location_level_id in (4, 5, 6) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_bad_city,
    sum(case when changing_quality_type = 'bad' and prev_location_level_id in (2, 3) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_bad_region,
    sum(case when changing_quality_type = 'bad' and prev_location_level_id = 1 and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_bad_russia,
    sum(case when subcategory_id is null and prev_location_id != location_id and eid = 2918 and close_by > 0 and category_id is not null and open_from = 'search' then events_count end) as loc_chng_category_level,
    sum(case when changing_geo_type = 'horizontal' and prev_location_level_id in (4, 5, 6) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_city_city,
    sum(case when changing_geo_type = 'expanded' and location_level_id in (2, 3) and prev_location_level_id in (4, 5, 6) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_city_region,
    sum(case when changing_geo_type = 'expanded' and location_level_id = 1 and prev_location_level_id in (4, 5, 6) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_city_russia,
    sum(case when subcategory_id is null and category_id is null and prev_location_id != location_id and eid = 2918 and close_by > 0 and open_from = 'search' then events_count end) as loc_chng_na_category_level,
    sum(case when changing_quality_type = 'neutral' and prev_location_level_id in (4, 5, 6) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_neutral_city,
    sum(case when changing_quality_type = 'neutral' and prev_location_level_id in (2, 3) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_neutral_region,
    sum(case when changing_quality_type = 'neutral' and prev_location_level_id = 1 and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_neutral_russia,
    sum(case when open_from = 'radius' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_radius,
    sum(case when changing_geo_type = 'detailed' and prev_location_level_id in (2, 3) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_region_city,
    sum(case when changing_geo_type = 'horizontal' and prev_location_level_id in (2, 3) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_region_region,
    sum(case when changing_geo_type = 'expanded' and prev_location_level_id in (2, 3) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_region_russia,
    sum(case when changing_geo_type = 'detailed' and location_level_id in (4, 5, 6) and prev_location_level_id = 1 and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_russia_city,
    sum(case when changing_geo_type = 'detailed' and location_level_id in (2, 3) and prev_location_level_id = 1 and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_russia_region,
    sum(case when open_from = 'search' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_search,
    sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 and category_id is not null and subcategory_id is not null and open_from = 'search' then events_count end) as loc_chng_subcategory_level,
    sum(case when changing_quality_type = 'suspicious' and prev_location_level_id in (4, 5, 6) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_suspicious_city,
    sum(case when changing_quality_type = 'suspicious' and prev_location_level_id in (2, 3) and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_suspicious_region,
    sum(case when changing_quality_type = 'suspicious' and prev_location_level_id = 1 and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng_suspicious_russia,
    sum(case when changing_geo_type = 'detailed' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_detailed_chng,
    sum(case when changing_geo_type = 'expanded' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_expanded_chng,
    sum(case when changing_geo_type = 'horizontal' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_horizontal_chng,
    sum(case when changing_quality_type = 'neutral' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_neutral_chng,
    sum(case when prev_location_id = location_id and eid = 2918 and close_by > 0 then events_count end) as loc_rechoice,
    sum(case when open_from = 'app settings' and prev_location_id = location_id and eid = 2918 and close_by > 0 then events_count end) as loc_rechoice_app_settings,
    sum(case when subcategory_id is null and prev_location_id = location_id and eid = 2918 and close_by > 0 and category_id is not null and open_from = 'search' then events_count end) as loc_rechoice_category_level,
    sum(case when subcategory_id is null and category_id is null and prev_location_id = location_id and eid = 2918 and close_by > 0 and open_from = 'search' then events_count end) as loc_rechoice_na_category_level,
    sum(case when open_from = 'search' and prev_location_id = location_id and eid = 2918 and close_by > 0 then events_count end) as loc_rechoice_search,
    sum(case when prev_location_id = location_id and eid = 2918 and close_by > 0 and category_id is not null and subcategory_id is not null and open_from = 'search' then events_count end) as loc_rechoice_subcategory_level,
    sum(case when changing_quality_type = 'suspicious' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_susp_chng,
    sum(case when eid = 2918 then events_count end) as loc_window_closings,
    sum(case when eid = 2916 then events_count end) as loc_window_opens,
    sum(case when open_from = 'app settings' and eid = 2916 then events_count end) as loc_window_opens_app_settings,
    sum(case when subcategory_id is null and category_id is not null and open_from = 'search' and eid = 2916 then events_count end) as loc_window_opens_category_level,
    sum(case when subcategory_id is null and category_id is null and open_from = 'search' and eid = 2916 then events_count end) as loc_window_opens_na_category_level,
    sum(case when open_from = 'radius' and eid = 2916 then events_count end) as loc_window_opens_radius,
    sum(case when open_from = 'search' and eid = 2916 then events_count end) as loc_window_opens_search,
    sum(case when category_id is not null and subcategory_id is not null and open_from = 'search' and eid = 2916 then events_count end) as loc_window_opens_subcategory_level,
    sum(case when eid = 2918 and close_by > 0 then events_count end) as loc_window_savings,
    sum(case when eid = 2918 and time_span > 0 then time_span end) as loc_window_time_span
from geo_loc_change t
;

create metrics geo_loc_change_cookie as
select
    sum(case when cnt_tooltip_accepts_city > 0 then 1 end) as default_loc_tooltip_accepts_city,
    sum(case when cnt_tooltip_accepts_region > 0 then 1 end) as default_loc_tooltip_accepts_region,
    sum(case when cnt_tooltip_accepts_russia > 0 then 1 end) as default_loc_tooltip_accepts_russia,
    sum(case when cnt_tooltip_not_accepts_city > 0 then 1 end) as default_loc_tooltip_declines_city,
    sum(case when cnt_tooltip_not_accepts_region > 0 then 1 end) as default_loc_tooltip_declines_region,
    sum(case when cnt_tooltip_not_accepts_russia > 0 then 1 end) as default_loc_tooltip_declines_russia,
    sum(case when laas_accepts > 0 then 1 end) as unq_laas_tooltip_accepts,
    sum(case when laas_accepts_change > 0 then 1 end) as unq_laas_tooltip_accepts_change,
    sum(case when laas_answers_change > 0 then 1 end) as unq_laas_tooltip_accepts_change_declines,
    sum(case when laas_answers > 0 then 1 end) as unq_laas_tooltip_accepts_declines,
    sum(case when laas_accepts_regular > 0 then 1 end) as unq_laas_tooltip_accepts_regular,
    sum(case when laas_answers_regular > 0 then 1 end) as unq_laas_tooltip_accepts_regular_declines,
    sum(case when laas_shows > 0 then 1 end) as unq_laas_tooltip_shows,
    sum(case when laas_shows_change > 0 then 1 end) as unq_laas_tooltip_shows_change,
    sum(case when laas_shows_regular > 0 then 1 end) as unq_laas_tooltip_shows_regular,
    sum(case when default_loc_tooltip_shows > 0 then 1 end) as users_default_loc_tooltip,
    sum(case when default_loc_tooltip_accepts > 0 then 1 end) as users_default_loc_tooltip_accepts,
    sum(case when default_loc_tooltip_declines > 0 then 1 end) as users_default_loc_tooltip_declines,
    sum(case when loc_bad_susp_chng > 0 then 1 end) as users_loc_bad_and_chng,
    sum(case when loc_bad_chng > 0 then 1 end) as users_loc_bad_chng,
    sum(case when loc_chng > 0 then 1 end) as users_loc_chng,
    sum(case when loc_detailed_chng > 0 then 1 end) as users_loc_detailed_chng,
    sum(case when loc_expanded_chng > 0 then 1 end) as users_loc_expanded_chng,
    sum(case when loc_horizontal_chng > 0 then 1 end) as users_loc_horizontal_chng,
    sum(case when loc_neutral_chng > 0 then 1 end) as users_loc_neutral_chng,
    sum(case when loc_rechoice > 0 then 1 end) as users_loc_rechoiced,
    sum(case when loc_susp_chng > 0 then 1 end) as users_loc_susp_chng,
    sum(case when loc_window_opens > 0 then 1 end) as users_loc_window_opens,
    sum(case when loc_window_opens_radius > 0 then 1 end) as users_loc_window_opens_radius,
    sum(case when loc_window_opens_search > 0 then 1 end) as users_loc_window_opens_search
from (
    select
        cookie_id, cookie,
        sum(case when location_level_id in (4, 5, 6) and tooltip_close_type = 'accept' and eid = 2914 then events_count end) as cnt_tooltip_accepts_city,
        sum(case when location_level_id in (2, 3) and tooltip_close_type = 'accept' and eid = 2914 then events_count end) as cnt_tooltip_accepts_region,
        sum(case when location_level_id = 1 and tooltip_close_type = 'accept' and eid = 2914 then events_count end) as cnt_tooltip_accepts_russia,
        sum(case when location_level_id in (4, 5, 6) and tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as cnt_tooltip_not_accepts_city,
        sum(case when location_level_id in (2, 3) and tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as cnt_tooltip_not_accepts_region,
        sum(case when location_level_id = 1 and tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as cnt_tooltip_not_accepts_russia,
        sum(case when tooltip_close_type = 'accept' and eid = 2914 then events_count end) as default_loc_tooltip_accepts,
        sum(case when tooltip_close_type = 'not accept' and eid = 2914 then events_count end) as default_loc_tooltip_declines,
        sum(case when eid = 2912 then events_count end) as default_loc_tooltip_shows,
        sum(case when tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts,
        sum(case when open_from_id = 'change' and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_change,
        sum(case when open_from_id = 'regular' and tooltip_close_type = 'accept' and eid = 4183 then events_count end) as laas_accepts_regular,
        sum(case when eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers,
        sum(case when open_from_id = 'change' and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_change,
        sum(case when open_from_id = 'regular' and eid = 4183 and (tooltip_close_type in ('accept', 'close')) then events_count end) as laas_answers_regular,
        sum(case when eid = 4183 then events_count end) as laas_shows,
        sum(case when open_from_id = 'change' and eid = 4183 then events_count end) as laas_shows_change,
        sum(case when open_from_id = 'regular' and eid = 4183 then events_count end) as laas_shows_regular,
        sum(case when changing_quality_type = 'bad' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_bad_chng,
        sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 and (changing_quality_type in ('bad', 'suspicious')) then events_count end) as loc_bad_susp_chng,
        sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng,
        sum(case when changing_geo_type = 'detailed' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_detailed_chng,
        sum(case when changing_geo_type = 'expanded' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_expanded_chng,
        sum(case when changing_geo_type = 'horizontal' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_horizontal_chng,
        sum(case when changing_quality_type = 'neutral' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_neutral_chng,
        sum(case when prev_location_id = location_id and eid = 2918 and close_by > 0 then events_count end) as loc_rechoice,
        sum(case when changing_quality_type = 'suspicious' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_susp_chng,
        sum(case when eid = 2916 then events_count end) as loc_window_opens,
        sum(case when open_from = 'radius' and eid = 2916 then events_count end) as loc_window_opens_radius,
        sum(case when open_from = 'search' and eid = 2916 then events_count end) as loc_window_opens_search
    from geo_loc_change t
    group by cookie_id, cookie
) _
;

create metrics geo_loc_change_session as
select
    sum(case when loc_bad_susp_chng > 0 then 1 end) as loc_bad_and_chng_sessions,
    sum(case when loc_bad_chng > 0 then 1 end) as loc_bad_chng_sessions,
    sum(case when loc_chng > 0 then 1 end) as loc_chng_sessions,
    sum(case when loc_neutral_chng > 0 then 1 end) as loc_neutral_chng_sessions,
    sum(case when loc_rechoice > 0 then 1 end) as loc_rechoiced_sessions,
    sum(case when loc_susp_chng > 0 then 1 end) as loc_susp_chng_sessions,
    sum(case when loc_window_closings > 0 then 1 end) as users_loc_window_closings
from (
    select
        cookie_id, session,
        sum(case when changing_quality_type = 'bad' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_bad_chng,
        sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 and (changing_quality_type in ('bad', 'suspicious')) then events_count end) as loc_bad_susp_chng,
        sum(case when prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_chng,
        sum(case when changing_quality_type = 'neutral' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_neutral_chng,
        sum(case when prev_location_id = location_id and eid = 2918 and close_by > 0 then events_count end) as loc_rechoice,
        sum(case when changing_quality_type = 'suspicious' and prev_location_id != location_id and eid = 2918 and close_by > 0 then events_count end) as loc_susp_chng,
        sum(case when eid = 2918 then events_count end) as loc_window_closings
    from geo_loc_change t
    group by cookie_id, session
) _
;
