create fact mnz_vas as
select
    :ab_start_date,
    t.amount,
    t.amount_net,
    t.event_date,
    t.is_classified,
    t.ispayment,
    t.isrevenue,
    t.product_subtype,
    t.product_type,
    t.start_date,
    t.transaction_counter,
    t.transaction_subtype,
    t.user_id as user,
    t.user_id
from dma.vo_mnz_vas_metrics t
;

create metrics mnz_vas_user as
select
    sum(case when vas_amount_net > 0 then 1 end) as users_vas,
    sum(case when vas_amount_net_activation > 0 then 1 end) as users_vas_activation,
    sum(case when vas_amount_net_bundle > 0 then 1 end) as users_vas_bundle,
    sum(case when vas_amount_net_bundle_max > 0 then 1 end) as users_vas_bundle_max,
    sum(case when vas_amount_net_bundle_mid > 0 then 1 end) as users_vas_bundle_mid,
    sum(case when vas_amount_net_bundle_start_date > 0 then 1 end) as users_vas_bundle_start_date,
    sum(case when vas_amount_net_fast > 0 then 1 end) as users_vas_fast,
    sum(case when vas_amount_net_highlight > 0 then 1 end) as users_vas_highlight,
    sum(case when vas_amount_net_highlight_start_date > 0 then 1 end) as users_vas_highlight_start_date,
    sum(case when vas_amount_net_performance > 0 then 1 end) as users_vas_performance,
    sum(case when vas_amount_net_performance_start_date > 0 then 1 end) as users_vas_performance_start_date,
    sum(case when vas_amount_net_premium > 0 then 1 end) as users_vas_premium,
    sum(case when vas_amount_net_pushup > 0 then 1 end) as users_vas_pushup,
    sum(case when vas_reserve_transactions > 0 then 1 end) as users_vas_reserve,
    sum(case when vas_reserve_transactions_bundle > 0 then 1 end) as users_vas_reserve_bundle,
    sum(case when vas_reserve_transactions_bundle_max > 0 then 1 end) as users_vas_reserve_bundle_max,
    sum(case when vas_reserve_transactions_bundle_mid > 0 then 1 end) as users_vas_reserve_bundle_mid,
    sum(case when vas_reserve_transactions_highlight > 0 then 1 end) as users_vas_reserve_highlight,
    sum(case when vas_reserve_transactions_performance > 0 then 1 end) as users_vas_reserve_performance,
    sum(case when vas_reserve_transactions_visual > 0 then 1 end) as users_vas_reserve_visual,
    sum(case when vas_reserve_transactions_x10_1 > 0 then 1 end) as users_vas_reserve_x10_1,
    sum(case when vas_reserve_transactions_x10_7 > 0 then 1 end) as users_vas_reserve_x10_7,
    sum(case when vas_reserve_transactions_x12_1 > 0 then 1 end) as users_vas_reserve_x12_1,
    sum(case when vas_reserve_transactions_x12_7 > 0 then 1 end) as users_vas_reserve_x12_7,
    sum(case when vas_reserve_transactions_x14_1 > 0 then 1 end) as users_vas_reserve_x14_1,
    sum(case when vas_reserve_transactions_x14_7 > 0 then 1 end) as users_vas_reserve_x14_7,
    sum(case when vas_reserve_transactions_x15_1 > 0 then 1 end) as users_vas_reserve_x15_1,
    sum(case when vas_reserve_transactions_x15_7 > 0 then 1 end) as users_vas_reserve_x15_7,
    sum(case when vas_reserve_transactions_x16_1 > 0 then 1 end) as users_vas_reserve_x16_1,
    sum(case when vas_reserve_transactions_x16_7 > 0 then 1 end) as users_vas_reserve_x16_7,
    sum(case when vas_reserve_transactions_x18_1 > 0 then 1 end) as users_vas_reserve_x18_1,
    sum(case when vas_reserve_transactions_x18_7 > 0 then 1 end) as users_vas_reserve_x18_7,
    sum(case when vas_reserve_transactions_x20_1 > 0 then 1 end) as users_vas_reserve_x20_1,
    sum(case when vas_reserve_transactions_x20_7 > 0 then 1 end) as users_vas_reserve_x20_7,
    sum(case when vas_reserve_transactions_x2_1 > 0 then 1 end) as users_vas_reserve_x2_1,
    sum(case when vas_reserve_transactions_x2_7 > 0 then 1 end) as users_vas_reserve_x2_7,
    sum(case when vas_reserve_transactions_x5_1 > 0 then 1 end) as users_vas_reserve_x5_1,
    sum(case when vas_reserve_transactions_x5_7 > 0 then 1 end) as users_vas_reserve_x5_7,
    sum(case when vas_reserve_transactions_xl > 0 then 1 end) as users_vas_reserve_xl,
    sum(case when vas_amount_net_start_date > 0 then 1 end) as users_vas_start_date,
    sum(case when vas_amount_net_turbo > 0 then 1 end) as users_vas_turbo,
    sum(case when vas_amount_net_vip > 0 then 1 end) as users_vas_vip,
    sum(case when vas_amount_net_visual > 0 then 1 end) as users_vas_visual,
    sum(case when vas_amount_net_visual_start_date > 0 then 1 end) as users_vas_visual_start_date,
    sum(case when vas_amount_net_x10_1 > 0 then 1 end) as users_vas_x10_1,
    sum(case when vas_amount_net_x10_7 > 0 then 1 end) as users_vas_x10_7,
    sum(case when vas_amount_net_x12_1 > 0 then 1 end) as users_vas_x12_1,
    sum(case when vas_amount_net_x12_7 > 0 then 1 end) as users_vas_x12_7,
    sum(case when vas_amount_net_x14_1 > 0 then 1 end) as users_vas_x14_1,
    sum(case when vas_amount_net_x14_7 > 0 then 1 end) as users_vas_x14_7,
    sum(case when vas_amount_net_x15_1 > 0 then 1 end) as users_vas_x15_1,
    sum(case when vas_amount_net_x15_7 > 0 then 1 end) as users_vas_x15_7,
    sum(case when vas_amount_net_x16_1 > 0 then 1 end) as users_vas_x16_1,
    sum(case when vas_amount_net_x16_7 > 0 then 1 end) as users_vas_x16_7,
    sum(case when vas_amount_net_x18_1 > 0 then 1 end) as users_vas_x18_1,
    sum(case when vas_amount_net_x18_7 > 0 then 1 end) as users_vas_x18_7,
    sum(case when vas_amount_net_x20_1 > 0 then 1 end) as users_vas_x20_1,
    sum(case when vas_amount_net_x20_7 > 0 then 1 end) as users_vas_x20_7,
    sum(case when vas_amount_net_x2_1 > 0 then 1 end) as users_vas_x2_1,
    sum(case when vas_amount_net_x2_7 > 0 then 1 end) as users_vas_x2_7,
    sum(case when vas_amount_net_x5_1 > 0 then 1 end) as users_vas_x5_1,
    sum(case when vas_amount_net_x5_7 > 0 then 1 end) as users_vas_x5_7,
    sum(case when vas_amount_net_xl > 0 then 1 end) as users_vas_xl,
    sum(case when vas_amount_net_xl_start_date > 0 then 1 end) as users_vas_xl_start_date
from (
    select
        user_id, user,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' then amount_net end) as vas_amount_net,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Activation' then amount_net end) as vas_amount_net_activation,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then amount_net end) as vas_amount_net_bundle,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then amount_net end) as vas_amount_net_bundle_max,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then amount_net end) as vas_amount_net_bundle_mid,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_bundle_start_date,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Fast package' then amount_net end) as vas_amount_net_fast,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then amount_net end) as vas_amount_net_highlight,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_highlight_start_date,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then amount_net end) as vas_amount_net_performance,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_performance_start_date,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Premium' then amount_net end) as vas_amount_net_premium,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Pushup' then amount_net end) as vas_amount_net_pushup,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_start_date,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Turbo package' then amount_net end) as vas_amount_net_turbo,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'VIP' then amount_net end) as vas_amount_net_vip,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then amount_net end) as vas_amount_net_visual,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_visual_start_date,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then amount_net end) as vas_amount_net_x10_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then amount_net end) as vas_amount_net_x10_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then amount_net end) as vas_amount_net_x12_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then amount_net end) as vas_amount_net_x12_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then amount_net end) as vas_amount_net_x14_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then amount_net end) as vas_amount_net_x14_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then amount_net end) as vas_amount_net_x15_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then amount_net end) as vas_amount_net_x15_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then amount_net end) as vas_amount_net_x16_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then amount_net end) as vas_amount_net_x16_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then amount_net end) as vas_amount_net_x18_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then amount_net end) as vas_amount_net_x18_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then amount_net end) as vas_amount_net_x20_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then amount_net end) as vas_amount_net_x20_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then amount_net end) as vas_amount_net_x2_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then amount_net end) as vas_amount_net_x2_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then amount_net end) as vas_amount_net_x5_1,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then amount_net end) as vas_amount_net_x5_7,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then amount_net end) as vas_amount_net_xl,
        sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_xl_start_date,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' then transaction_counter end) as vas_reserve_transactions,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then transaction_counter end) as vas_reserve_transactions_bundle,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then transaction_counter end) as vas_reserve_transactions_bundle_max,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then transaction_counter end) as vas_reserve_transactions_bundle_mid,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then transaction_counter end) as vas_reserve_transactions_highlight,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then transaction_counter end) as vas_reserve_transactions_performance,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then transaction_counter end) as vas_reserve_transactions_visual,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then transaction_counter end) as vas_reserve_transactions_x10_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then transaction_counter end) as vas_reserve_transactions_x10_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then transaction_counter end) as vas_reserve_transactions_x12_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then transaction_counter end) as vas_reserve_transactions_x12_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then transaction_counter end) as vas_reserve_transactions_x14_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then transaction_counter end) as vas_reserve_transactions_x14_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then transaction_counter end) as vas_reserve_transactions_x15_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then transaction_counter end) as vas_reserve_transactions_x15_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then transaction_counter end) as vas_reserve_transactions_x16_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then transaction_counter end) as vas_reserve_transactions_x16_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then transaction_counter end) as vas_reserve_transactions_x18_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then transaction_counter end) as vas_reserve_transactions_x18_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then transaction_counter end) as vas_reserve_transactions_x20_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then transaction_counter end) as vas_reserve_transactions_x20_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then transaction_counter end) as vas_reserve_transactions_x2_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then transaction_counter end) as vas_reserve_transactions_x2_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then transaction_counter end) as vas_reserve_transactions_x5_1,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then transaction_counter end) as vas_reserve_transactions_x5_7,
        sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then transaction_counter end) as vas_reserve_transactions_xl
    from mnz_vas t
    group by user_id, user
) _
;

create metrics mnz_vas as
select
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' then amount end) as vas_amount,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Activation' then amount end) as vas_amount_activation,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then amount end) as vas_amount_bundle,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then amount end) as vas_amount_bundle_max,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then amount end) as vas_amount_bundle_mid,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then amount end) as vas_amount_bundle_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Fast package' then amount end) as vas_amount_fast,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then amount end) as vas_amount_highlight,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' and start_date >= :ab_start_date then amount end) as vas_amount_highlight_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' then amount_net end) as vas_amount_net,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Activation' then amount_net end) as vas_amount_net_activation,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then amount_net end) as vas_amount_net_bundle,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then amount_net end) as vas_amount_net_bundle_max,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then amount_net end) as vas_amount_net_bundle_mid,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_bundle_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Fast package' then amount_net end) as vas_amount_net_fast,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then amount_net end) as vas_amount_net_highlight,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_highlight_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then amount_net end) as vas_amount_net_performance,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_performance_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Premium' then amount_net end) as vas_amount_net_premium,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Pushup' then amount_net end) as vas_amount_net_pushup,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Turbo package' then amount_net end) as vas_amount_net_turbo,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'VIP' then amount_net end) as vas_amount_net_vip,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then amount_net end) as vas_amount_net_visual,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_visual_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then amount_net end) as vas_amount_net_x10_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then amount_net end) as vas_amount_net_x10_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then amount_net end) as vas_amount_net_x12_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then amount_net end) as vas_amount_net_x12_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then amount_net end) as vas_amount_net_x14_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then amount_net end) as vas_amount_net_x14_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then amount_net end) as vas_amount_net_x15_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then amount_net end) as vas_amount_net_x15_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then amount_net end) as vas_amount_net_x16_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then amount_net end) as vas_amount_net_x16_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then amount_net end) as vas_amount_net_x18_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then amount_net end) as vas_amount_net_x18_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then amount_net end) as vas_amount_net_x20_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then amount_net end) as vas_amount_net_x20_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then amount_net end) as vas_amount_net_x2_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then amount_net end) as vas_amount_net_x2_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then amount_net end) as vas_amount_net_x5_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then amount_net end) as vas_amount_net_x5_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then amount_net end) as vas_amount_net_xl,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' and start_date >= :ab_start_date then amount_net end) as vas_amount_net_xl_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then amount end) as vas_amount_performance,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then amount end) as vas_amount_performance_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Premium' then amount end) as vas_amount_premium,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Pushup' then amount end) as vas_amount_pushup,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then amount end) as vas_amount_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Turbo package' then amount end) as vas_amount_turbo,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'VIP' then amount end) as vas_amount_vip,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then amount end) as vas_amount_visual,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then amount end) as vas_amount_visual_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then amount end) as vas_amount_x10_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then amount end) as vas_amount_x10_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then amount end) as vas_amount_x12_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then amount end) as vas_amount_x12_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then amount end) as vas_amount_x14_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then amount end) as vas_amount_x14_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then amount end) as vas_amount_x15_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then amount end) as vas_amount_x15_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then amount end) as vas_amount_x16_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then amount end) as vas_amount_x16_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then amount end) as vas_amount_x18_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then amount end) as vas_amount_x18_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then amount end) as vas_amount_x20_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then amount end) as vas_amount_x20_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then amount end) as vas_amount_x2_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then amount end) as vas_amount_x2_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then amount end) as vas_amount_x5_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then amount end) as vas_amount_x5_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then amount end) as vas_amount_xl,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' and start_date >= :ab_start_date then amount end) as vas_amount_xl_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' then amount end) as vas_clean_reserved_amount,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then amount end) as vas_clean_reserved_amount_bundle,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then amount end) as vas_clean_reserved_amount_bundle_max,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then amount end) as vas_clean_reserved_amount_bundle_mid,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then amount end) as vas_clean_reserved_amount_bundle_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then amount end) as vas_clean_reserved_amount_highlight,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' then amount_net end) as vas_clean_reserved_amount_net,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then amount_net end) as vas_clean_reserved_amount_net_bundle,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then amount_net end) as vas_clean_reserved_amount_net_bundle_max,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then amount_net end) as vas_clean_reserved_amount_net_bundle_mid,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then amount_net end) as vas_clean_reserved_amount_net_bundle_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then amount_net end) as vas_clean_reserved_amount_net_highlight,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then amount_net end) as vas_clean_reserved_amount_net_performance,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then amount_net end) as vas_clean_reserved_amount_net_performance_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then amount_net end) as vas_clean_reserved_amount_net_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then amount_net end) as vas_clean_reserved_amount_net_visual,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then amount_net end) as vas_clean_reserved_amount_net_visual_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then amount_net end) as vas_clean_reserved_amount_net_x10_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then amount_net end) as vas_clean_reserved_amount_net_x10_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then amount_net end) as vas_clean_reserved_amount_net_x12_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then amount_net end) as vas_clean_reserved_amount_net_x12_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then amount_net end) as vas_clean_reserved_amount_net_x14_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then amount_net end) as vas_clean_reserved_amount_net_x14_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then amount_net end) as vas_clean_reserved_amount_net_x15_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then amount_net end) as vas_clean_reserved_amount_net_x15_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then amount_net end) as vas_clean_reserved_amount_net_x16_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then amount_net end) as vas_clean_reserved_amount_net_x16_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then amount_net end) as vas_clean_reserved_amount_net_x18_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then amount_net end) as vas_clean_reserved_amount_net_x18_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then amount_net end) as vas_clean_reserved_amount_net_x20_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then amount_net end) as vas_clean_reserved_amount_net_x20_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then amount_net end) as vas_clean_reserved_amount_net_x2_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then amount_net end) as vas_clean_reserved_amount_net_x2_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then amount_net end) as vas_clean_reserved_amount_net_x5_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then amount_net end) as vas_clean_reserved_amount_net_x5_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then amount_net end) as vas_clean_reserved_amount_net_xl,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then amount end) as vas_clean_reserved_amount_performance,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then amount end) as vas_clean_reserved_amount_performance_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then amount end) as vas_clean_reserved_amount_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then amount end) as vas_clean_reserved_amount_visual,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then amount end) as vas_clean_reserved_amount_visual_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then amount end) as vas_clean_reserved_amount_x10_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then amount end) as vas_clean_reserved_amount_x10_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then amount end) as vas_clean_reserved_amount_x12_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then amount end) as vas_clean_reserved_amount_x12_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then amount end) as vas_clean_reserved_amount_x14_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then amount end) as vas_clean_reserved_amount_x14_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then amount end) as vas_clean_reserved_amount_x15_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then amount end) as vas_clean_reserved_amount_x15_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then amount end) as vas_clean_reserved_amount_x16_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then amount end) as vas_clean_reserved_amount_x16_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then amount end) as vas_clean_reserved_amount_x18_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then amount end) as vas_clean_reserved_amount_x18_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then amount end) as vas_clean_reserved_amount_x20_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then amount end) as vas_clean_reserved_amount_x20_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then amount end) as vas_clean_reserved_amount_x2_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then amount end) as vas_clean_reserved_amount_x2_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then amount end) as vas_clean_reserved_amount_x5_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then amount end) as vas_clean_reserved_amount_x5_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then amount end) as vas_clean_reserved_amount_xl,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' then transaction_counter end) as vas_reserve_transactions,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then transaction_counter end) as vas_reserve_transactions_bundle,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then transaction_counter end) as vas_reserve_transactions_bundle_max,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then transaction_counter end) as vas_reserve_transactions_bundle_mid,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then transaction_counter end) as vas_reserve_transactions_bundle_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then transaction_counter end) as vas_reserve_transactions_highlight,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' and start_date >= :ab_start_date then transaction_counter end) as vas_reserve_transactions_highlight_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then transaction_counter end) as vas_reserve_transactions_performance,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then transaction_counter end) as vas_reserve_transactions_performance_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then transaction_counter end) as vas_reserve_transactions_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then transaction_counter end) as vas_reserve_transactions_visual,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then transaction_counter end) as vas_reserve_transactions_visual_start_date,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then transaction_counter end) as vas_reserve_transactions_x10_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then transaction_counter end) as vas_reserve_transactions_x10_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then transaction_counter end) as vas_reserve_transactions_x12_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then transaction_counter end) as vas_reserve_transactions_x12_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then transaction_counter end) as vas_reserve_transactions_x14_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then transaction_counter end) as vas_reserve_transactions_x14_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then transaction_counter end) as vas_reserve_transactions_x15_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then transaction_counter end) as vas_reserve_transactions_x15_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then transaction_counter end) as vas_reserve_transactions_x16_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then transaction_counter end) as vas_reserve_transactions_x16_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then transaction_counter end) as vas_reserve_transactions_x18_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then transaction_counter end) as vas_reserve_transactions_x18_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then transaction_counter end) as vas_reserve_transactions_x20_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then transaction_counter end) as vas_reserve_transactions_x20_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then transaction_counter end) as vas_reserve_transactions_x2_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then transaction_counter end) as vas_reserve_transactions_x2_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then transaction_counter end) as vas_reserve_transactions_x5_1,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then transaction_counter end) as vas_reserve_transactions_x5_7,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then transaction_counter end) as vas_reserve_transactions_xl,
    sum(case when ispayment = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' and start_date >= :ab_start_date then transaction_counter end) as vas_reserve_transactions_xl_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Activation' then transaction_counter end) as vas_transactions_activation,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and start_date >= :ab_start_date then transaction_counter end) as vas_transactions_bundle_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Fast package' then transaction_counter end) as vas_transactions_fast,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' then transaction_counter end) as vas_transactions_highlight,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Highlight' and start_date >= :ab_start_date then transaction_counter end) as vas_transactions_highlight_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' then transaction_counter end) as vas_transactions_mnz,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' then transaction_counter end) as vas_transactions_mnz_bundle,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'max' then transaction_counter end) as vas_transactions_mnz_bundle_max,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'bundle' and transaction_subtype = 'mid' then transaction_counter end) as vas_transactions_mnz_bundle_mid,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' then transaction_counter end) as vas_transactions_mnz_performance,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' then transaction_counter end) as vas_transactions_mnz_visual,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_1' then transaction_counter end) as vas_transactions_mnz_x10_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x10_7' then transaction_counter end) as vas_transactions_mnz_x10_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_1' then transaction_counter end) as vas_transactions_mnz_x12_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x12_7' then transaction_counter end) as vas_transactions_mnz_x12_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_1' then transaction_counter end) as vas_transactions_mnz_x14_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x14_7' then transaction_counter end) as vas_transactions_mnz_x14_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_1' then transaction_counter end) as vas_transactions_mnz_x15_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x15_7' then transaction_counter end) as vas_transactions_mnz_x15_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_1' then transaction_counter end) as vas_transactions_mnz_x16_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x16_7' then transaction_counter end) as vas_transactions_mnz_x16_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_1' then transaction_counter end) as vas_transactions_mnz_x18_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x18_7' then transaction_counter end) as vas_transactions_mnz_x18_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_1' then transaction_counter end) as vas_transactions_mnz_x20_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x20_7' then transaction_counter end) as vas_transactions_mnz_x20_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_1' then transaction_counter end) as vas_transactions_mnz_x2_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x2_7' then transaction_counter end) as vas_transactions_mnz_x2_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_1' then transaction_counter end) as vas_transactions_mnz_x5_1,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'x5_7' then transaction_counter end) as vas_transactions_mnz_x5_7,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'performance' and start_date >= :ab_start_date then transaction_counter end) as vas_transactions_performance_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Premium' then transaction_counter end) as vas_transactions_premium,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Pushup' then transaction_counter end) as vas_transactions_pushup,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and start_date >= :ab_start_date then transaction_counter end) as vas_transactions_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'Turbo package' then transaction_counter end) as vas_transactions_turbo,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'VIP' then transaction_counter end) as vas_transactions_vip,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and product_subtype = 'visual' and start_date >= :ab_start_date then transaction_counter end) as vas_transactions_visual_start_date,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' then transaction_counter end) as vas_transactions_xl,
    sum(case when isrevenue = True and is_classified = True and product_type = 'vas' and transaction_subtype = 'XL' and start_date >= :ab_start_date then transaction_counter end) as vas_transactions_xl_start_date
from mnz_vas t
;
