create fact notification as
select
    t.event_date::date as __date__,
    t.app_pushes_no_data,
    t.app_pushes_open,
    t.app_pushes_prepared,
    t.app_pushes_price_all_no_data,
    t.app_pushes_price_all_open,
    t.app_pushes_price_all_prepared,
    t.app_pushes_price_all_to_provider,
    t.app_pushes_price_all_to_receiver,
    t.app_pushes_price_no_data,
    t.app_pushes_price_open,
    t.app_pushes_price_prepared,
    t.app_pushes_price_to_provider,
    t.app_pushes_price_to_receiver,
    t.app_pushes_rec_marketing_no_data,
    t.app_pushes_rec_marketing_open,
    t.app_pushes_rec_marketing_prepared,
    t.app_pushes_rec_marketing_to_provider,
    t.app_pushes_rec_marketing_to_receiver,
    t.app_pushes_sav_search_no_data,
    t.app_pushes_sav_search_open,
    t.app_pushes_sav_search_prepared,
    t.app_pushes_sav_search_to_provider,
    t.app_pushes_sav_search_to_receiver,
    t.app_pushes_to_provider,
    t.app_pushes_to_receiver,
    t.cookie_id,
    t.event_date,
    t.participant_id as participant
from dma.vo_notification t
;

create metrics notification as
select
    sum(app_pushes_no_data) as push_no_data,
    sum(app_pushes_open) as push_open,
    sum(app_pushes_prepared) as push_prepared,
    sum(app_pushes_price_all_no_data) as push_price_all_no_data,
    sum(app_pushes_price_all_open) as push_price_all_open,
    sum(app_pushes_price_all_prepared) as push_price_all_prepared,
    sum(app_pushes_price_all_to_provider) as push_price_all_to_provider,
    sum(app_pushes_price_all_to_receiver) as push_price_all_to_receiver,
    sum(app_pushes_price_no_data) as push_price_no_data,
    sum(app_pushes_price_open) as push_price_open,
    sum(app_pushes_price_prepared) as push_price_prepared,
    sum(app_pushes_price_to_provider) as push_price_to_provider,
    sum(app_pushes_price_to_receiver) as push_price_to_receiver,
    sum(app_pushes_rec_marketing_no_data) as push_rec_marketing_no_data,
    sum(app_pushes_rec_marketing_open) as push_rec_marketing_open,
    sum(app_pushes_rec_marketing_prepared) as push_rec_marketing_prepared,
    sum(app_pushes_rec_marketing_to_provider) as push_rec_marketing_to_provider,
    sum(app_pushes_rec_marketing_to_receiver) as push_rec_marketing_to_receiver,
    sum(app_pushes_sav_search_no_data) as push_sav_search_no_data,
    sum(app_pushes_sav_search_open) as push_sav_search_open,
    sum(app_pushes_sav_search_prepared) as push_sav_search_prepared,
    sum(app_pushes_sav_search_to_provider) as push_sav_search_to_provider,
    sum(app_pushes_sav_search_to_receiver) as push_sav_search_to_receiver,
    sum(app_pushes_to_provider) as push_to_provider,
    sum(app_pushes_to_receiver) as push_to_receiver
from notification t
;

create metrics notification_participant as
select
    sum(case when push_no_data > 0 then 1 end) as user_push_no_data,
    sum(case when push_price_no_data > 0 then 1 end) as user_push_no_data_price,
    sum(case when push_price_all_no_data > 0 then 1 end) as user_push_no_data_price_all,
    sum(case when push_rec_marketing_no_data > 0 then 1 end) as user_push_no_data_rec_marketing,
    sum(case when push_sav_search_no_data > 0 then 1 end) as user_push_no_data_sav,
    sum(case when push_open > 0 then 1 end) as user_push_open,
    sum(case when push_price_open > 0 then 1 end) as user_push_open_price,
    sum(case when push_price_all_open > 0 then 1 end) as user_push_open_price_all,
    sum(case when push_rec_marketing_open > 0 then 1 end) as user_push_open_rec_marketing,
    sum(case when push_sav_search_open > 0 then 1 end) as user_push_open_sav,
    sum(case when push_prepared > 0 then 1 end) as user_push_prepared,
    sum(case when push_price_prepared > 0 then 1 end) as user_push_prepared_price,
    sum(case when push_price_all_prepared > 0 then 1 end) as user_push_prepared_price_all,
    sum(case when push_rec_marketing_prepared > 0 then 1 end) as user_push_prepared_rec_marketing,
    sum(case when push_sav_search_prepared > 0 then 1 end) as user_push_prepared_sav,
    sum(case when push_to_provider > 0 then 1 end) as user_push_to_provider,
    sum(case when push_price_to_provider > 0 then 1 end) as user_push_to_provider_price,
    sum(case when push_price_all_to_provider > 0 then 1 end) as user_push_to_provider_price_all,
    sum(case when push_rec_marketing_to_provider > 0 then 1 end) as user_push_to_provider_rec_marketing,
    sum(case when push_sav_search_to_provider > 0 then 1 end) as user_push_to_provider_sav,
    sum(case when push_to_receiver > 0 then 1 end) as user_push_to_receiver,
    sum(case when push_price_to_receiver > 0 then 1 end) as user_push_to_receiver_price,
    sum(case when push_price_all_to_receiver > 0 then 1 end) as user_push_to_receiver_price_all,
    sum(case when push_rec_marketing_to_receiver > 0 then 1 end) as user_push_to_receiver_rec_marketing,
    sum(case when push_sav_search_to_receiver > 0 then 1 end) as user_push_to_receiver_sav
from (
    select
        cookie_id, participant,
        sum(app_pushes_no_data) as push_no_data,
        sum(app_pushes_open) as push_open,
        sum(app_pushes_prepared) as push_prepared,
        sum(app_pushes_price_all_no_data) as push_price_all_no_data,
        sum(app_pushes_price_all_open) as push_price_all_open,
        sum(app_pushes_price_all_prepared) as push_price_all_prepared,
        sum(app_pushes_price_all_to_provider) as push_price_all_to_provider,
        sum(app_pushes_price_all_to_receiver) as push_price_all_to_receiver,
        sum(app_pushes_price_no_data) as push_price_no_data,
        sum(app_pushes_price_open) as push_price_open,
        sum(app_pushes_price_prepared) as push_price_prepared,
        sum(app_pushes_price_to_provider) as push_price_to_provider,
        sum(app_pushes_price_to_receiver) as push_price_to_receiver,
        sum(app_pushes_rec_marketing_no_data) as push_rec_marketing_no_data,
        sum(app_pushes_rec_marketing_open) as push_rec_marketing_open,
        sum(app_pushes_rec_marketing_prepared) as push_rec_marketing_prepared,
        sum(app_pushes_rec_marketing_to_provider) as push_rec_marketing_to_provider,
        sum(app_pushes_rec_marketing_to_receiver) as push_rec_marketing_to_receiver,
        sum(app_pushes_sav_search_no_data) as push_sav_search_no_data,
        sum(app_pushes_sav_search_open) as push_sav_search_open,
        sum(app_pushes_sav_search_prepared) as push_sav_search_prepared,
        sum(app_pushes_sav_search_to_provider) as push_sav_search_to_provider,
        sum(app_pushes_sav_search_to_receiver) as push_sav_search_to_receiver,
        sum(app_pushes_to_provider) as push_to_provider,
        sum(app_pushes_to_receiver) as push_to_receiver
    from notification t
    group by cookie_id, participant
) _
;
