create fact perf_mobile as
select
    t.observation_date::date as __date__,
    t.api_exceptions,
    t.cookie_id,
    t.duration,
    t.duration_events,
    t.error_dialog_type,
    t.events,
    t.events_p25,
    t.events_p50,
    t.events_p75,
    t.events_p95,
    t.exceptions,
    t.frequent_screens_enabled,
    t.is_core_content,
    t.network_exceptions,
    t.observation_date,
    t.response,
    t.session_duration,
    t.session_duration_events,
    t.sessions,
    t.sessions_p25,
    t.sessions_p50,
    t.sessions_p75,
    t.sessions_p95,
    t.sessions_sla,
    t.silent_exceptions,
    t.stage_name,
    t.was_error_in_screen
from dma.o_perf_mobile t
;

create metrics perf_mobile as
select
    sum(case when is_core_content = True then exceptions end) as any_core_exceptions,
    sum(exceptions) as any_exceptions,
    sum(case when stage_name = 'ServerLoading' then api_exceptions end) as api_exceptions,
    sum(case when stage_name = 'DI' then events end) as cnt_di_events,
    sum(case when stage_name = 'DI' then events_p25 end) as cnt_di_events_p25,
    sum(case when stage_name = 'DI' then events_p50 end) as cnt_di_events_p50,
    sum(case when stage_name = 'DI' then events_p75 end) as cnt_di_events_p75,
    sum(case when stage_name = 'DI' then events_p95 end) as cnt_di_events_p95,
    sum(case when stage_name = 'DI' then session_duration end) as cnt_di_session_duration,
    sum(case when stage_name = 'DI' then session_duration_events end) as cnt_di_session_duration_events,
    sum(case when stage_name = 'Draw_appstart' then session_duration end) as cnt_draw_appstart_session_duration,
    sum(case when stage_name = 'Draw_appstart' then session_duration_events end) as cnt_draw_appstart_session_duration_events,
    sum(case when stage_name = 'Draw_appstart' then sessions end) as cnt_draw_appstart_sessions,
    sum(case when stage_name = 'Draw_appstart' then sessions_p25 end) as cnt_draw_appstart_sessions_p25,
    sum(case when stage_name = 'Draw_appstart' then sessions_p50 end) as cnt_draw_appstart_sessions_p50,
    sum(case when stage_name = 'Draw_appstart' then sessions_p75 end) as cnt_draw_appstart_sessions_p75,
    sum(case when stage_name = 'Draw_appstart' then sessions_p95 end) as cnt_draw_appstart_sessions_p95,
    sum(case when stage_name = 'Draw' then duration end) as cnt_draw_duration,
    sum(case when stage_name = 'Draw' then duration_events end) as cnt_draw_duration_events,
    sum(case when stage_name = 'Draw' then events end) as cnt_draw_events,
    sum(case when stage_name = 'Draw' then ifnull(events, 0) + ifnull(exceptions, 0) end) as cnt_draw_events_exceptions,
    sum(case when stage_name = 'Draw' and frequent_screens_enabled = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as cnt_draw_events_exceptions_fr_screens_on,
    sum(case when stage_name = 'Draw' then events_p25 end) as cnt_draw_events_p25,
    sum(case when stage_name = 'Draw' then events_p50 end) as cnt_draw_events_p50,
    sum(case when stage_name = 'Draw' then events_p75 end) as cnt_draw_events_p75,
    sum(case when stage_name = 'Draw' then events_p95 end) as cnt_draw_events_p95,
    sum(case when stage_name = 'Draw' then exceptions end) as cnt_draw_exceptions,
    sum(case when stage_name = 'Draw' then session_duration end) as cnt_draw_session_duration,
    sum(case when stage_name = 'Draw' then session_duration_events end) as cnt_draw_session_duration_events,
    sum(case when stage_name = 'Draw' then sessions end) as cnt_draw_sessions,
    sum(case when stage_name = 'Draw' then sessions_p25 end) as cnt_draw_sessions_p25,
    sum(case when stage_name = 'Draw' then sessions_p50 end) as cnt_draw_sessions_p50,
    sum(case when stage_name = 'Draw' then sessions_p75 end) as cnt_draw_sessions_p75,
    sum(case when stage_name = 'Draw' then sessions_p95 end) as cnt_draw_sessions_p95,
    sum(case when stage_name = 'Draw' then sessions_sla end) as cnt_draw_sessions_sla,
    sum(case when stage_name = 'Init_appstart' then duration end) as cnt_init_appstart_duration,
    sum(case when stage_name = 'Init_appstart' then session_duration end) as cnt_init_appstart_session_duration,
    sum(case when stage_name = 'Init_appstart' then session_duration_events end) as cnt_init_appstart_session_duration_events,
    sum(case when stage_name = 'Init_appstart' then sessions end) as cnt_init_appstart_sessions,
    sum(case when stage_name = 'Init_appstart' then sessions_p25 end) as cnt_init_appstart_sessions_p25,
    sum(case when stage_name = 'Init_appstart' then sessions_p50 end) as cnt_init_appstart_sessions_p50,
    sum(case when stage_name = 'Init_appstart' then sessions_p75 end) as cnt_init_appstart_sessions_p75,
    sum(case when stage_name = 'Init_appstart' then sessions_p95 end) as cnt_init_appstart_sessions_p95,
    sum(case when stage_name = 'Init' then duration end) as cnt_init_duration,
    sum(case when stage_name = 'Init' then duration_events end) as cnt_init_duration_events,
    sum(case when stage_name = 'Init' then events end) as cnt_init_events,
    sum(case when stage_name = 'Init' then events_p25 end) as cnt_init_events_p25,
    sum(case when stage_name = 'Init' then events_p50 end) as cnt_init_events_p50,
    sum(case when stage_name = 'Init' then events_p75 end) as cnt_init_events_p75,
    sum(case when stage_name = 'Init' then events_p95 end) as cnt_init_events_p95,
    sum(case when stage_name = 'Init' then session_duration end) as cnt_init_session_duration,
    sum(case when stage_name = 'Init' then session_duration_events end) as cnt_init_session_duration_events,
    sum(case when stage_name = 'Init' then sessions end) as cnt_init_sessions,
    sum(case when stage_name = 'Init' then sessions_p25 end) as cnt_init_sessions_p25,
    sum(case when stage_name = 'Init' then sessions_p50 end) as cnt_init_sessions_p50,
    sum(case when stage_name = 'Init' then sessions_p75 end) as cnt_init_sessions_p75,
    sum(case when stage_name = 'Init' then sessions_p95 end) as cnt_init_sessions_p95,
    sum(case when stage_name = 'Init' then sessions_sla end) as cnt_init_sessions_sla,
    sum(case when stage_name = 'LocalLoading' then duration end) as cnt_localloading_duration,
    sum(case when stage_name = 'LocalLoading' then duration_events end) as cnt_localloading_duration_events,
    sum(case when stage_name = 'LocalLoading' then events end) as cnt_localloading_events,
    sum(case when stage_name = 'LocalLoading' then events_p25 end) as cnt_localloading_events_p25,
    sum(case when stage_name = 'LocalLoading' then events_p50 end) as cnt_localloading_events_p50,
    sum(case when stage_name = 'LocalLoading' then events_p75 end) as cnt_localloading_events_p75,
    sum(case when stage_name = 'LocalLoading' then events_p95 end) as cnt_localloading_events_p95,
    sum(case when stage_name = 'LocalLoading' then session_duration end) as cnt_localloading_session_duration,
    sum(case when stage_name = 'LocalLoading' then session_duration_events end) as cnt_localloading_session_duration_events,
    sum(case when stage_name = 'Prepare' then duration end) as cnt_prepare_duration,
    sum(case when stage_name = 'Prepare' then duration_events end) as cnt_prepare_duration_events,
    sum(case when stage_name = 'Prepare' then events end) as cnt_prepare_events,
    sum(case when stage_name = 'Prepare' then ifnull(events, 0) + ifnull(exceptions, 0) end) as cnt_prepare_events_exceptions,
    sum(case when stage_name = 'Prepare' then events_p25 end) as cnt_prepare_events_p25,
    sum(case when stage_name = 'Prepare' then events_p50 end) as cnt_prepare_events_p50,
    sum(case when stage_name = 'Prepare' then events_p75 end) as cnt_prepare_events_p75,
    sum(case when stage_name = 'Prepare' then events_p95 end) as cnt_prepare_events_p95,
    sum(case when stage_name = 'Prepare' then exceptions end) as cnt_prepare_exceptions,
    sum(case when stage_name = 'Prepare' then session_duration end) as cnt_prepare_session_duration,
    sum(case when stage_name = 'Prepare' then session_duration_events end) as cnt_prepare_session_duration_events,
    sum(case when stage_name = 'ServerLoading' then duration end) as cnt_serverloading_duration,
    sum(case when stage_name = 'ServerLoading' then duration_events end) as cnt_serverloading_duration_events,
    sum(case when stage_name = 'ServerLoading' then events end) as cnt_serverloading_events,
    sum(case when stage_name = 'ServerLoading' then ifnull(events, 0) + ifnull(exceptions, 0) end) as cnt_serverloading_events_exceptions,
    sum(case when stage_name = 'ServerLoading' then events_p25 end) as cnt_serverloading_events_p25,
    sum(case when stage_name = 'ServerLoading' then events_p50 end) as cnt_serverloading_events_p50,
    sum(case when stage_name = 'ServerLoading' then events_p75 end) as cnt_serverloading_events_p75,
    sum(case when stage_name = 'ServerLoading' then events_p95 end) as cnt_serverloading_events_p95,
    sum(case when stage_name = 'ServerLoading' then exceptions end) as cnt_serverloading_exceptions,
    sum(case when stage_name = 'ServerLoading' then session_duration end) as cnt_serverloading_session_duration,
    sum(case when stage_name = 'ServerLoading' then session_duration_events end) as cnt_serverloading_session_duration_events,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and is_core_content = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_core_exceptions,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'failed-to-load-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_failed_to_load,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'failed-to-perform-action-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_failed_to_perform_action,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'failed-to-reload-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_failed_to_reload,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'no-internet-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_no_internet,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'somehow-else-displayed-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_somehow_else_displayed,
    sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'unknown-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_unknown,
    sum(case when stage_name = 'Draw' and is_core_content = True then exceptions end) as draw_core_exceptions,
    sum(case when stage_name = 'Draw' and response = 'failed-to-load-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_failed_to_load,
    sum(case when stage_name = 'Draw' and response = 'failed-to-perform-action-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_failed_to_perform_action,
    sum(case when stage_name = 'Draw' and response = 'failed-to-reload-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_failed_to_reload,
    sum(case when stage_name = 'Draw' and response = 'no-data-placeholder' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_data_placeholder,
    sum(case when stage_name in ('Draw', 'ServerLoading') and response = 'no-data-placeholder' and was_error_in_screen = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_data_placeholder_error,
    sum(case when stage_name in ('Draw', 'ServerLoading') and response = 'no-data-placeholder' and was_error_in_screen = False then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_data_placeholder_no_error,
    sum(case when stage_name = 'Draw' and response = 'no-internet-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_internet,
    sum(case when stage_name = 'Draw' and response = 'nothing-found-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_nothing_found,
    sum(case when stage_name = 'Draw' and response = 'somehow-else-displayed-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_somehow_else_displayed,
    sum(case when stage_name = 'Draw' and response = 'something-went-wrong-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_something_went_wrong,
    sum(case when stage_name = 'Draw' and response = 'unknown-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_unknown,
    sum(case when stage_name = 'Draw' and (response not in ('no-data-placeholder', 'ok') or response = 'no-data-placeholder' and was_error_in_screen = True) then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_new_exceptions,
    sum(case when frequent_screens_enabled = True and stage_name = 'Draw' and (response not in ('no-data-placeholder', 'ok') or response = 'no-data-placeholder' and was_error_in_screen = True) then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_new_exceptions_fr_screens_on,
    sum(case when stage_name = 'Draw' and response not in ('no-data-placeholder', 'ok') then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_new_exceptions_wo_no_data,
    sum(case when stage_name = 'Draw' and (response = 'ok' or response = 'no-data-placeholder' and was_error_in_screen = False) then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_ok_events,
    sum(case when stage_name = 'Init_appstart' then duration_events end) as init_appstart_duration_events,
    sum(case when stage_name = 'Init_appstart' then events end) as init_appstart_events,
    sum(case when stage_name = 'Init_appstart' then ifnull(events, 0) + ifnull(exceptions, 0) end) as init_appstart_events_exceptions,
    sum(case when stage_name = 'Init_appstart' then events_p25 end) as init_appstart_events_p25,
    sum(case when stage_name = 'Init_appstart' then events_p50 end) as init_appstart_events_p50,
    sum(case when stage_name = 'Init_appstart' then events_p75 end) as init_appstart_events_p75,
    sum(case when stage_name = 'Init_appstart' then events_p95 end) as init_appstart_events_p95,
    sum(case when stage_name = 'Init_appstart' then exceptions end) as init_appstart_exceptions,
    sum(case when stage_name = 'ServerLoading' then network_exceptions end) as netwok_exceptions,
    sum(case when stage_name = 'Prepare' and is_core_content = True then exceptions end) as prepare_core_exceptions,
    sum(case when stage_name = 'ServerLoading' and is_core_content = True then exceptions end) as serverloading_core_exceptions,
    sum(case when stage_name = 'ServerLoading' then silent_exceptions end) as silent_exceptions,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and is_core_content = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_core_exceptions,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' then exceptions end) as toast_exceptions,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'failed-to-load-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_failed_to_load,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'failed-to-perform-action-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_failed_to_perform_action,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'failed-to-reload-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_failed_to_reload,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'no-internet-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_no_internet,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'somehow-else-displayed-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_somehow_else_displayed,
    sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'unknown-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_unknown
from perf_mobile t
;

create metrics perf_mobile_cookie_id as
select
    sum(case when api_exceptions > 0 then 1 end) as user_api_exceptions,
    sum(case when any_core_exceptions > 0 then 1 end) as user_core_exceptions,
    sum(case when dialog_core_exceptions > 0 then 1 end) as user_dialog_core_exceptions,
    sum(case when dialog_exceptions > 0 then 1 end) as user_dialog_exceptions,
    sum(case when dialog_exceptions_failed_to_load > 0 then 1 end) as user_dialog_exceptions_failed_to_load,
    sum(case when dialog_exceptions_failed_to_perform_action > 0 then 1 end) as user_dialog_exceptions_failed_to_perform_action,
    sum(case when dialog_exceptions_failed_to_reload > 0 then 1 end) as user_dialog_exceptions_failed_to_reload,
    sum(case when dialog_exceptions_no_internet > 0 then 1 end) as user_dialog_exceptions_no_internet,
    sum(case when dialog_exceptions_somehow_else_displayed > 0 then 1 end) as user_dialog_exceptions_somehow_else_displayed,
    sum(case when dialog_exceptions_unknown > 0 then 1 end) as user_dialog_exceptions_unknown,
    sum(case when draw_core_exceptions > 0 then 1 end) as user_draw_core_exceptions,
    sum(case when cnt_draw_events_exceptions_fr_screens_on > 0 then 1 end) as user_draw_events_exceptions_fr_screens_on,
    sum(case when cnt_draw_exceptions > 0 then 1 end) as user_draw_exceptions,
    sum(case when draw_exceptions_failed_to_load > 0 then 1 end) as user_draw_exceptions_failed_to_load,
    sum(case when draw_exceptions_failed_to_perform_action > 0 then 1 end) as user_draw_exceptions_failed_to_perform_action,
    sum(case when draw_exceptions_failed_to_reload > 0 then 1 end) as user_draw_exceptions_failed_to_reload,
    sum(case when draw_exceptions_no_data_placeholder > 0 then 1 end) as user_draw_exceptions_no_data_placeholder,
    sum(case when draw_exceptions_no_data_placeholder_error > 0 then 1 end) as user_draw_exceptions_no_data_placeholder_error,
    sum(case when draw_exceptions_no_data_placeholder_no_error > 0 then 1 end) as user_draw_exceptions_no_data_placeholder_no_error,
    sum(case when draw_exceptions_no_internet > 0 then 1 end) as user_draw_exceptions_no_internet,
    sum(case when draw_exceptions_nothing_found > 0 then 1 end) as user_draw_exceptions_nothing_found,
    sum(case when draw_exceptions_somehow_else_displayed > 0 then 1 end) as user_draw_exceptions_somehow_else_displayed,
    sum(case when draw_exceptions_something_went_wrong > 0 then 1 end) as user_draw_exceptions_something_went_wrong,
    sum(case when draw_exceptions_unknown > 0 then 1 end) as user_draw_exceptions_unknown,
    sum(case when draw_new_exceptions > 0 then 1 end) as user_draw_new_exceptions,
    sum(case when draw_new_exceptions > 9 then 1 end) as user_draw_new_exceptions_10plus,
    sum(case when draw_new_exceptions > 1 then 1 end) as user_draw_new_exceptions_2plus,
    sum(case when draw_new_exceptions > 4 then 1 end) as user_draw_new_exceptions_5plus,
    sum(case when draw_new_exceptions_fr_screens_on > 0 then 1 end) as user_draw_new_exceptions_fr_screens_on,
    sum(case when draw_new_exceptions_wo_no_data > 0 then 1 end) as user_draw_new_exceptions_wo_no_data,
    sum(case when draw_ok_events > 0 then 1 end) as user_draw_ok_events,
    sum(case when any_exceptions > 0 then 1 end) as user_exceptions,
    sum(case when netwok_exceptions > 0 then 1 end) as user_netwok_exceptions,
    sum(case when api_exceptions > 0 then 1 end) as user_prepare_core_exceptions,
    sum(case when cnt_prepare_exceptions > 0 then 1 end) as user_prepare_exceptions,
    sum(case when silent_exceptions > 0 then 1 end) as user_serverloading_core_exceptions,
    sum(case when cnt_serverloading_exceptions > 0 then 1 end) as user_serverloading_exceptions,
    sum(case when silent_exceptions > 0 then 1 end) as user_silent_exceptions,
    sum(case when toast_core_exceptions > 0 then 1 end) as user_toast_core_exceptions,
    sum(case when toast_exceptions > 0 then 1 end) as user_toast_exceptions,
    sum(case when toast_exceptions_failed_to_load > 0 then 1 end) as user_toast_exceptions_failed_to_load,
    sum(case when toast_exceptions_failed_to_perform_action > 0 then 1 end) as user_toast_exceptions_failed_to_perform_action,
    sum(case when toast_exceptions_failed_to_reload > 0 then 1 end) as user_toast_exceptions_failed_to_reload,
    sum(case when toast_exceptions_no_internet > 0 then 1 end) as user_toast_exceptions_no_internet,
    sum(case when toast_exceptions_somehow_else_displayed > 0 then 1 end) as user_toast_exceptions_somehow_else_displayed,
    sum(case when toast_exceptions_unknown > 0 then 1 end) as user_toast_exceptions_unknown
from (
    select
        cookie_id, cookie_id,
        sum(case when is_core_content = True then exceptions end) as any_core_exceptions,
        sum(exceptions) as any_exceptions,
        sum(case when stage_name = 'ServerLoading' then api_exceptions end) as api_exceptions,
        sum(case when stage_name = 'Draw' and frequent_screens_enabled = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as cnt_draw_events_exceptions_fr_screens_on,
        sum(case when stage_name = 'Draw' then exceptions end) as cnt_draw_exceptions,
        sum(case when stage_name = 'Prepare' then exceptions end) as cnt_prepare_exceptions,
        sum(case when stage_name = 'ServerLoading' then exceptions end) as cnt_serverloading_exceptions,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and is_core_content = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_core_exceptions,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'failed-to-load-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_failed_to_load,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'failed-to-perform-action-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_failed_to_perform_action,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'failed-to-reload-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_failed_to_reload,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'no-internet-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_no_internet,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'somehow-else-displayed-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_somehow_else_displayed,
        sum(case when stage_name = 'Draw' and error_dialog_type is not null and response = 'unknown-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as dialog_exceptions_unknown,
        sum(case when stage_name = 'Draw' and is_core_content = True then exceptions end) as draw_core_exceptions,
        sum(case when stage_name = 'Draw' and response = 'failed-to-load-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_failed_to_load,
        sum(case when stage_name = 'Draw' and response = 'failed-to-perform-action-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_failed_to_perform_action,
        sum(case when stage_name = 'Draw' and response = 'failed-to-reload-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_failed_to_reload,
        sum(case when stage_name = 'Draw' and response = 'no-data-placeholder' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_data_placeholder,
        sum(case when stage_name in ('Draw', 'ServerLoading') and response = 'no-data-placeholder' and was_error_in_screen = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_data_placeholder_error,
        sum(case when stage_name in ('Draw', 'ServerLoading') and response = 'no-data-placeholder' and was_error_in_screen = False then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_data_placeholder_no_error,
        sum(case when stage_name = 'Draw' and response = 'no-internet-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_no_internet,
        sum(case when stage_name = 'Draw' and response = 'nothing-found-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_nothing_found,
        sum(case when stage_name = 'Draw' and response = 'somehow-else-displayed-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_somehow_else_displayed,
        sum(case when stage_name = 'Draw' and response = 'something-went-wrong-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_something_went_wrong,
        sum(case when stage_name = 'Draw' and response = 'unknown-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_exceptions_unknown,
        sum(case when stage_name = 'Draw' and (response not in ('no-data-placeholder', 'ok') or response = 'no-data-placeholder' and was_error_in_screen = True) then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_new_exceptions,
        sum(case when frequent_screens_enabled = True and stage_name = 'Draw' and (response not in ('no-data-placeholder', 'ok') or response = 'no-data-placeholder' and was_error_in_screen = True) then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_new_exceptions_fr_screens_on,
        sum(case when stage_name = 'Draw' and response not in ('no-data-placeholder', 'ok') then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_new_exceptions_wo_no_data,
        sum(case when stage_name = 'Draw' and (response = 'ok' or response = 'no-data-placeholder' and was_error_in_screen = False) then ifnull(events, 0) + ifnull(exceptions, 0) end) as draw_ok_events,
        sum(case when stage_name = 'ServerLoading' then network_exceptions end) as netwok_exceptions,
        sum(case when stage_name = 'ServerLoading' then silent_exceptions end) as silent_exceptions,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and is_core_content = True then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_core_exceptions,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' then exceptions end) as toast_exceptions,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'failed-to-load-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_failed_to_load,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'failed-to-perform-action-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_failed_to_perform_action,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'failed-to-reload-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_failed_to_reload,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'no-internet-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_no_internet,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'somehow-else-displayed-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_somehow_else_displayed,
        sum(case when stage_name = 'Draw' and error_dialog_type = 'toast' and response = 'unknown-error' then ifnull(events, 0) + ifnull(exceptions, 0) end) as toast_exceptions_unknown
    from perf_mobile t
    group by cookie_id, cookie_id
) _
;
