with /*+ENABLE_WITH_CLAUSE_MATERIALIZATION */
bs_users as (
    select distinct item_user_id as user_id
    from dma.buyer_stream
    where event_date::date between :first_date::date and :last_date::date
        and item_user_id is not null
)
select
    ss.platform_id,
    ss.event_date,
    ss.cookie_id,
    ss.user_id,
    ss.session_no,
    ss.item_id,
    ss.item_user_id,
    ss.eid,
    ss.x,
    ss.query_id,
    -- для того, чтобы метрики с query одинаково считать на buyer_stream и clickstream_sparse
    case when ss.query_id is not null then 'q' else '' end as q,
    coalesce(ss.item_count,0) as item_count,
    coalesce(ss.base_item_count,0) as base_item_count,
    ss.page_no,
    NVL(ss.rec_position, 0) as rec_position,
    ss.from_page,
    ss.item_vas_flags,
    ss.phone_view_source,
    ss.item_x_type % 2 as item_x_type,
    ss.x_eid,
    case when ss.x_eid is not null then coalesce(ss.search_flags,0) end as search_flags,
    coalesce(ss.item_flags,0) as item_flags,
    coalesce(ss.other_flags,0) as other_flags,
    ss.x_from_page,
    ss.search_sort,
    ss.search_query_type,
    ss.item_serp_flags,
    ss.is_human_dev                                              as is_human,
    ss.search_radius::varchar                                    as search_radius,
    ss.district_count,
    ss.metro_count,
    hash(ss.item_id, ss.x, ss.eid)                              as item_x,
    ss.location_id,
    ss.microcat_id,
    ss.item_engines,
    hash(ss.location_id, ss.session_no, ss.microcat_id)         as location_session_microcat,
    acc.SFAccount_Type as SFAccount_Type,
    case when ss.eid in (401, 2574, 2732) then 1 when ss.eid = 402 then -1 end as favorites_net,
    case when ss.eid in (451) then 1 when ss.eid = 452 then -1 end as comparisons_net,
    -- Dimensions -----------------------------------------------------------------------------------------------------
    cm.vertical_id                                               as vertical_id,
    cm.logical_category_id                                       as logical_category_id,
    cm.category_id                                               as category_id,
    cm.subcategory_id                                            as subcategory_id,
    cm.Param1_microcat_id                                        as param1_id,
    cm.Param2_microcat_id                                        as param2_id,
    cm.Param3_microcat_id                                        as param3_id,
    cm.Param4_microcat_id                                        as param4_id,
    decode(cl.level, 3, cl.ParentLocation_id, cl.Location_id)    as region_id,
    decode(cl.level, 3, cl.Location_id, null)                    as city_id,
    cl.LocationGroup_id                                          as location_group_id,
    cl.City_Population_Group                                     as population_group,
    cl.Logical_Level                                             as location_level_id,
    ss.rec_engine_id,
    en.Name                                                      as engine,
    cmx.vertical_id                                              as x_vertical_id,
    cmx.logical_category_id                                      as x_logical_category_id,
    cmx.category_id                                              as x_category_id,
    cmx.subcategory_id                                           as x_subcategory_id,
    cmx.Param1_microcat_id                                       as x_param1_id,
    cmx.Param2_microcat_id                                       as x_param2_id,
    cmx.Param3_microcat_id                                       as x_param3_id,
    cmx.Param4_microcat_id                                       as x_param4_id,
    decode(clx.level, 3, clx.ParentLocation_id, clx.Location_id) as x_region_id,
    decode(clx.level, 3, clx.Location_id, null)                  as x_city_id,
    clx.LocationGroup_id                                         as x_location_group_id,
    clx.City_Population_Group                                    as x_population_group,
    clx.Logical_Level                                            as x_location_level_id,
    case
       when (item_vas_flags & (1 << 12) > 0 or item_vas_flags & (1 << 13) > 0) then 2
       when (item_vas_flags & (1 << 14) > 0 or item_vas_flags & (1 << 15) > 0) then 5
       when (item_vas_flags & (1 << 16) > 0 or item_vas_flags & (1 << 17) > 0) then 10
       else 1
    end                                                          as vas_power,
    case
        when (ss.item_flags & (1 << 18) > 0) then 5 -- Новое
        when (ss.item_flags & (1 << 19) > 0) then 1 -- Б/у
        when (ss.item_flags & (1 << 20) > 0) then 2 -- Битый
        when (ss.item_flags & (1 << 21) > 0) then 4 -- Не битый
        else 0 --Undefined
    end                                                          as condition_id,
    ((case when ss.x_eid is not null then coalesce(ss.search_flags, 0) end & 16) > 0)::int as onmap,
    (case when ss.x_eid is not null then coalesce(ss.search_flags, 0) end >> 10) & 0xFFFFF as search_features,
    ubb.track_id is not null as new_user_btc,
    asd.is_asd,
    asd.asd_user_group_id,
    coalesce(usm.user_segment_market, ls.segment) as user_segment_market,
    ss.item_rnk,
    ss.boost_class_id,
    3 AS multiplier_3,
    5 AS multiplier_5,
    10 AS multiplier_10,
    0 as cnt_reg_in_s,
0 as searches_witcher_new_auto,
0 as cnt_reg_in_s,
0 as cnt_btc_rec_i2i_mp,
0 as c_witcher_funnel_any,
0 as item_views_client,
0 as serp_empty,
0 as cnt_cs_ph_fav_list,
0 as cnt_iv_wtc_reg,
0 as cnt_fav_rec,
0 as cnt_btc_serp_perfvas_x2_1,
0 as cnt_btc_s_radius,
0 as cnt_cs_vec,
0 as cnt_fav_s_metro,
0 as cnt_s_wtc_dlv,
0 as cnt_cs_developer_rec_i2i,
0 as cnt_btc_wtc_new_auto,
0 as buyer_target_clicks_with_shop_id,
0 as total_delivery_click_all_services_rec_i2i,
0 as cnt_iv_s_radius,
0 as cnt_btc_s_distr_metro_road,
0 as radius_200_searches,
0 as cnt_ph_realty_development,
0 as searches_district,
0 as item_views_from_fs,
0 as cnt_btc_rec_perfvas_x10_7,
0 as cnt_iv_s_metro,
0 as cnt_btc_wtc_mp,
0 as cnt_fav_from_map_s_area,
0 as searches_serp_with_mp,
0 as cnt_cs_rec_perfvas_x5_7,
0 as cnt_users_1plus_actions,
0 as radius_10_searches,
0 as cnt_cs_developer_from_map,
0 as iv_re_agency,
0 as cnt_fav_wtc_new_auto,
0 as cnt_cs_rec_i2i_vip,
0 as iv_witcher_funnel_regions,
0 as cnt_iv_from_map,
0 as total_delivery_contact_all_services_serp,
0 as services_main_pages,
0 as cnt_iv_rec_perfvas_x10_1,
0 as btc_witcher_funnel_regions,
0 as cnt_btc_rec_perfvas_x5_7,
0 as cnt_btc_rec_perfvas_x2_7,
0 as cnt_btc_s_query,
0 as cnt_cs_rec_vas,
0 as serp_without_query_small,
0 as searches_from_witcher_marketplace,
0 as cnt_s_distr_with_iv_metro_road,
0 as searches_any_ext_block,
0 as total_delivery_contact_all_services,
0 as cnt_btc,
0 as cnt_cs_from_map_s_area,
0 as cnt_iv_s_map_area,
0 as radius_big_searches,
0 as searches_with_query_date_sort,
0 as radius_500_searches,
0 as cnt_sessions_btc,
0 as total_delivery_click_all_services_serp,
0 as radius_1000_searches,
0 as cnt_s_iv_date_sort,
0 as searches_from_witcher_regions,
0 as searches_metro,
0 as base_serp_with_query_small,
0 as item_views_metageo,
0 as noncapital_city_level_searches,
0 as cnt_cs_wtc_new_auto,
0 as cnt_btc_developer_from_map,
0 as first_messages,
0 as cnt_fav_s,
0 as cnt_fav_wtc_reg,
0 as cnt_iv_rec_job_ast,
0 as federal_city_level_searches,
0 as favorites_removed,
0 as cnt_cs_rec_u2i_vas,
0 as cnt_cs_rec_i2i_premium,
0 as cnt_iv_serp_perfvas_x10_1,
0 as cnt_s_u2i_c,
0 as cnt_iv_rec_perfvas_x5_7,
0 as head_main_pages,
0 as c_not_actual_calendar,
0 as total_delivery_click_all_services_rec_u2i,
0 as cnt_s_iv_default_sort,
0 as cnt_cs_s_radius,
0 as searches_price_sort,
0 as cnt_fav_s_map_area,
0 as cnt_iv_rec_i2i_mp,
0 as city_level_searches,
0 as btc_perfvas_x5_7,
0 as cnt_cs_push,
0 as total_delivery_contact_mp,
0 as recblock_shows,
0 as cnt_cs_rec_premium,
0 as item_views_perfvas_x2_1,
0 as cnt_iv_wtc_dlv_new_auto_flats_reg,
0 as item_views_client_rec_from_msg,
0 as iv_not_actual_calendar,
0 as cnt_btc_serp_perfvas_x2_7,
0 as serp_with_query_empty,
0 as searches_metageo,
0 as searches_extra_regions,
0 as saved_searches,
0 as cnt_cs_wtc_dlv,
0 as cnt_fav_rec_i2i_push,
0 as radius_25_searches,
0 as total_delivery_btc,
0 as cnt_s_wtc_mp,
0 as serp_small,
0 as cnt_fav_rec_i2i,
0 as cnt_book_dlv_fmsg_ph,
0 as cnt_cs_rec_u2i_vip,
0 as realty_development_phone_views,
0 as searches_geo,
0 as cnt_cs_rec_perfvas_x2_1,
0 as cnt_btc_wtc_dlv_new_auto_flats_reg,
0 as cnt_btc_rec_perfvas_x10_1,
0 as fav_added_developer,
0 as cnt_cs_rec_mp,
0 as item_views_with_shop_id,
0 as fav_witcher_funnel_new_flats,
0 as cnt_iv_rec_push,
0 as c_witcher_funnel_new_auto,
0 as cnt_cs_rec_perfvas_x10_7,
0 as cnt_cs_rec,
0 as cnt_btc_rec_vas,
0 as cnt_iv_wtc_reg_s_from,
0 as base_serp_with_query_empty,
0 as cnt_btc_rec_i2i,
0 as iv_leadgen_item,
0 as cnt_cs_developer_rec,
0 as filters_price_searches,
0 as cnt_s_btc_price_sort,
0 as cnt_book_dlv_flow_beginings_fmsg_ph_realty_development,
0 as item_views,
0 as cnt_sessions_active,
0 as searches_with_mp_items,
0 as total_delivery_confirm_mp,
0 as cnt_iv_s_item_attr_mp,
0 as c_leadgen_item,
0 as cnt_iv_qrm,
0 as phone_views_with_shop_id,
0 as iv_witcher_funnel_new_auto,
0 as realty_dev_views,
0 as cnt_fav_dlv,
0 as cnt_btc_developer_rec_u2i,
0 as favorites_added_mp,
0 as btc_actual_calendar,
0 as job_ast_shows,
0 as cnt_btc_any_ext_block,
0 as cnt_cs_dlv,
0 as cnt_fav_wtc_dlv,
0 as searches_date_sort,
0 as cnt_btc_reg,
0 as cnt_iv_rec_i2i_push,
0 as cnt_cs_msg_rec_u2i,
0 as cnt_btc_qrm,
0 as cnt_cs_rec_i2i_vas,
0 as vertical_main_pages,
0 as searches_serp_extra_vector,
0 as iv_witcher_funnel_new_flats,
0 as cnt_cs_ph_s_item_attr,
0 as search_u2i,
0 as cnt_cs_developer_rec_u2i,
0 as booking_created_short_rent,
0 as c_actual_calendar,
0 as cnt_btc_s_distr,
0 as btc_perfvas_x5_1,
0 as serp_empty_mp,
0 as cnt_cs_serp_perfvas_x2_1,
0 as cnt_cs_wtc_mp,
0 as contacts_total_vas,
0 as cnt_btc_push,
0 as cnt_btc_serp_perfvas_x10_1,
0 as searches_from_witcher_delivery,
0 as total_courier_btc,
0 as cnt_ph_item_right_top_snippet_xlvas,
0 as cnt_cs_s_grouped_doubles,
0 as item_views_perfvas_x5_1,
0 as cnt_iv_developer_rec_i2i,
0 as fav_witcher_funnel_new_auto,
0 as cnt_btc_serp_perfvas_x5_1,
0 as cnt_fav_vip,
0 as cnt_fav_wtc_mp,
0 as item_views_perfvas_x10_1,
0 as cnt_fav_rec_u2i_vas,
0 as radius_50_searches,
0 as cnt_iv_rec_u2i_mp,
0 as cnt_btc_vas,
0 as phone_views_total_vip,
0 as cnt_iv_reg,
0 as cnt_iv_rec_u2i_push,
0 as cnt_iv_wtc_mp,
0 as cnt_fav_s_radius,
0 as cnt_btc_wtc_dlv,
0 as cnt_iv_wtc_mp_s_from,
0 as base_serp_without_query_empty,
0 as cnt_btc_from_map,
0 as btc_perfvas_x2_1,
0 as btc_mp,
0 as radius_300_searches,
0 as phone_views_total_vas,
0 as cnt_iv_from_map_s_area,
0 as cnt_fav_rec_premium,
0 as searches_default_sort,
0 as searches_with_filter_any,
0 as cnt_cs_serp_perfvas_x10_7,
0 as searches_with_query,
0 as cnt_cities_in_s,
0 as total_delivery_widget_mp,
0 as total_delivery_contact_all_services_fav,
0 as cnt_iv_rec_i2i_premium,
0 as cnt_fav_rec_i2i_premium,
0 as contacts_perfvas_x2_7,
0 as searches_from_witcher_any,
0 as cnt_iv_wtc_new_auto,
0 as default_radius_searches,
0 as item_views_total_vip,
0 as btc_witcher_funnel_delivery,
0 as cnt_fav_push,
0 as cnt_cs_rec_push,
0 as iv_re_private,
0 as cnt_cs_rec_u2i,
0 as cnt_fav_from_map,
0 as fav_witcher_funnel_any,
0 as cnt_iv_rec_mp,
0 as cnt_cs_ph_rec_i2i,
0 as cnt_iv_s_road,
0 as cnt_iv_any_ext_block,
0 as cnt_fav_rec_job_ast,
0 as btc_perfvas_x10_1,
0 as cnt_iv_premium,
0 as cnt_iv_grouped,
0 as cnt_fav_vas,
0 as cnt_cs_msg_s_item_attr,
0 as btc_pro_image,
0 as favorites_list_views,
0 as cnt_cs_vas,
0 as cnt_fav_rec_u2i,
0 as delivery_orders_created,
0 as searches_road,
0 as cnt_book_dlv_favorites_added_fmsg_ph_realty_development,
0 as cnt_cs_rec_u2i_push,
0 as radius_5_searches,
0 as cnt_cs_serp_perfvas_x5_1,
0 as cnt_s_u2i_iv,
0 as cnt_iv_serp_perfvas_x5_1,
0 as fav_witcher_funnel_delivery,
0 as total_delivery_click_all_services_fav,
0 as searches_serp_extra_regions,
0 as cnt_iv_s_item_attr,
0 as cnt_iv_dlv,
0 as radius_400_searches,
0 as cnt_fav_wtc_new_flats,
0 as cnt_btc_s_noquery,
0 as cnt_fav_rec_u2i_premium,
0 as c_witcher_funnel_new_flats,
0 as cnt_btc_rec_u2i_mp,
0 as cnt_s_query_iv,
0 as cnt_iv_vip,
0 as contacts,
0 as cnt_iv_rec_u2i_premium,
0 as searches_radius,
0 as btc_witcher_funnel_new_auto,
0 as radius_1_searches,
0 as russia_level_searches,
0 as cnt_iv_grouped_doubles,
0 as btc_witcher_funnel_marketplace,
0 as cnt_cs_premium,
0 as capital_city_level_searches,
0 as item_views_total_premium,
0 as serp_small_mp,
0 as c_re_private,
0 as btc_perfvas_x2_7,
0 as cnt_cs_rec_u2i_mp,
0 as cnt_cs_rec_vip,
0 as total_courier_widget,
0 as shortcut_clicks,
0 as cnt_fav_s_road,
0 as iv_developer,
0 as iv_actual_calendar,
0 as cnt_cs_s_saved,
0 as cnt_fav_rec_i2i_vip,
0 as searches_local_geo,
0 as item_views_with_available_msg,
0 as cnt_cs_s_item_attr_mp,
0 as searches_extra_delivery,
0 as searches_without_query,
0 as c_pro_image,
0 as cnt_iv_rec_u2i_vip,
0 as phone_view_button_clicks,
0 as cnt_iv_s_distr,
0 as searches_with_query_mp,
0 as cnt_btc_vec,
0 as cnt_btc_rec_perfvas_x2_1,
0 as cnt_s_btc_date_sort,
0 as recblock_shows_u2i,
0 as radius_100_searches,
0 as write_button_clicks,
0 as searches_without_query_mp,
0 as cnt_cs_s_metro,
0 as iv_developer_search,
0 as cnt_btc_rec,
0 as bt_clicks,
0 as cnt_iv_s_u2i,
0 as cnt_btc_s_u2i,
0 as searches_serp_mp,
0 as contacts_perfvas_x5_1,
0 as searches_group_doubles,
0 as total_delivery_contact_all_services_rec_u2i,
0 as cnt_s_u2i_btc,
0 as searches_group,
0 as cnt_iv_rec_perfvas_x5_1,
0 as searches_extra_vector,
0 as cnt_btc_shopx,
0 as cnt_btc_s_saved,
0 as cnt_cs_qrm,
0 as cnt_iv_rec_s,
0 as total_delivery_click_mp,
0 as cnt_btc_wtc_new_flats,
0 as radius_0_searches,
0 as re_main_pages,
0 as cnt_iv_rec_i2i_vas,
0 as cnt_iv_push,
0 as c_witcher_funnel_regions,
0 as cnt_btc_rec_perfvas_x5_1,
0 as cnt_cs_rec_s,
0 as cnt_fav_s_saved,
0 as c_witcher_funnel_marketplace,
0 as cnt_iv_rec_perfvas_x2_7,
0 as phone_views,
0 as realty_dev_phone_views,
0 as total_delivery_contact_all_services_rec_i2i,
0 as cnt_btc_s_road,
0 as cnt_cs_s_distr_metro_road,
0 as cnt_s_btc_default_sort,
0 as item_views_perfvas_x2_7,
0 as searches_with_filter,
0 as cnt_cs_wtc_reg,
0 as saved_searches_added,
0 as cnt_btc_s_item_attr_mp,
0 as all_main_pages,
0 as cnt_cs_msg_rec_i2i,
0 as base_serp_empty,
0 as searches_mp,
0 as searches_with_price_filter,
0 as cnt_iv_rec_premium,
0 as radius_short_searches,
0 as c_developer_search,
0 as cnt_iv_vec,
0 as cnt_cs_rec_perfvas_x2_7,
0 as cnt_iv_developer_rec_u2i,
0 as cnt_fav_rec_i2i_vas,
0 as total_courier_contact,
0 as cnt_iv_wtc_dlv_new_auto_flats_reg_s_from,
0 as advertisement_page_views,
0 as contacts_perfvas_x10_1,
0 as cnt_fav_shopx,
0 as total_delivery_click_all_services,
0 as cnt_iv_rec,
0 as cnt_s_extra_any_ext_block,
0 as cnt_cs_s_road,
0 as cnt_cs_shopx,
0 as cnt_btc_dlv,
0 as c_re_agency,
0 as cnt_btc_s_map_area,
0 as cnt_cs_wtc_new_flats,
0 as cnt_fav_rec_u2i_vip,
0 as phone_views_total_push,
0 as cnt_iv_rec_u2i,
0 as cnt_iv_shopx,
0 as iv_witcher_funnel_marketplace,
0 as cnt_iv_developer_rec,
0 as cnt_btc_rec_u2i,
0 as cnt_btc_job_ast,
0 as cnt_fav_list_iv,
0 as btc_witcher_funnel_new_flats,
0 as cnt_iv_wtc_dlv,
0 as cnt_fav_reg,
0 as cnt_s_query,
0 as c_developer,
0 as not_default_radius_searches,
0 as cnt_cs_any_ext_block,
0 as phone_views_total_premium,
0 as searches_shop_empty,
0 as cnt_btc_s_metro,
0 as cnt_cs_rec_u2i_premium,
0 as cnt_btc_wtc_reg,
0 as cnt_cs_rec_i2i_mp,
0 as contacts_perfvas_x5_7,
0 as cnt_cs_serp_perfvas_x5_7,
0 as cnt_cs_vip,
0 as cnt_iv_serp_perfvas_x2_1,
0 as item_views_mp,
0 as buyer_target_clicks_metageo,
0 as cnt_iv_rec_vas,
0 as contacts_metageo,
0 as cnt_favorites_net,
0 as cnt_iv_s_saved,
0 as write_button_clicks_with_shop_id,
0 as cnt_fav_rec_u2i_push,
0 as iv_witcher_funnel_any,
0 as cnt_fav_s_u2i,
0 as phone_views_total,
0 as serp_without_query_empty,
0 as searches_shop,
0 as cnt_iv_rec_perfvas_x2_1,
0 as cnt_cs_serp_perfvas_x2_7,
0 as base_serp_without_query_small,
0 as cnt_fav_rec_vas,
0 as cnt_cs_rec_i2i_push,
0 as item_views_total_vas,
0 as cnt_cs_wtc_dlv_new_auto_flats_reg,
0 as phone_views_snippet,
0 as cnt_book_dlv_fmsg_ph_item_right_top_realty_development,
0 as cnt_cs_msg_fav_list,
0 as cnt_cs_rec_perfvas_x10_1,
0 as cnt_s_wtc_dlv_new_auto_flats_reg,
0 as total_districts_in_searches,
0 as cnt_btc_serp_perfvas_x5_7,
0 as cnt_cs_rec_i2i,
0 as cnt_cs_s_item_attr,
0 as item_views_perfvas_x10_7,
0 as searches_from_witcher_new_auto,
0 as item_views_total_push,
0 as searches_from_witcher_new_flats,
0 as contacts_perfvas_x10_7,
0 as searches_serp_extra_quorum,
0 as cnt_fav_premium,
0 as searches_witcher_new_flats,
0 as cnt_iv_rec_u2i_vas,
0 as total_courier_click,
0 as cnt_cs_s_map_area,
0 as cnt_cs_s_distr,
0 as recblock_shows_i2i,
0 as cnt_iv_wtc_new_flats_s_from,
0 as favorites_added,
0 as serp_with_query_small,
0 as btc_not_actual_calendar,
0 as cnt_cs_ph_rec_u2i,
0 as searches_shop_small,
0 as cnt_c_rec_job_ast,
0 as base_serp_small,
0 as cnt_fav_rec_vip,
0 as searches_serp_extra_delivery,
0 as cnt_iv_serp_perfvas_x10_7,
0 as cnt_btc_serp_perfvas_x10_7,
0 as cnt_dlv_flow_beginings,
0 as cnt_btc_rec_mp,
0 as cnt_btc_developer_rec_i2i,
0 as cnt_iv_wtc_new_flats,
0 as cnt_s_query_c,
0 as first_messages_vas,
0 as btc_developer,
0 as cnt_iv_rec_i2i,
0 as btc_developer_search,
0 as searches,
0 as cnt_iv_serp_perfvas_x2_7,
0 as cnt_cs_s_u2i,
0 as cnt_cs_rec_perfvas_x5_1,
0 as cnt_s_iv_price_sort,
0 as cnt_s_noquery_c,
0 as cnt_iv_s_filter_price,
0 as cnt_cs_reg,
0 as cnt_btc_from_map_s_area,
0 as fav_witcher_funnel_marketplace,
0 as cnt_btc_s_distr_metro_radius_road,
0 as cnt_s_without_query,
0 as cnt_iv_rec_i2i_vip,
0 as cnt_iv_rec_perfvas_x10_7,
0 as filters_rubricator_searches,
0 as cnt_iv_wtc_new_auto_s_from,
0 as cnt_fav_rec_push,
0 as btc_witcher_funnel_any,
0 as cnt_iv_serp_perfvas_x5_7,
0 as c_witcher_funnel_delivery,
0 as cnt_iv_rec_vip,
0 as searches_serp,
0 as cnt_cs_from_map,
0 as cnt_cs_fav_list,
0 as cnt_cs_serp_perfvas_x10_1,
0 as cnt_btc_views_s_filter_price,
0 as fav_witcher_funnel_regions,
0 as iv_witcher_funnel_delivery,
0 as cnt_iv_wtc_dlv_s_from,
0 as transport_main_pages,
0 as searches_with_shop_id,
0 as contacts_perfvas_x2_1,
0 as cnt_iv_vas,
0 as cnt_btc_vip,
0 as fav_added_with_shop_id,
0 as searches_witcher_regions,
0 as searches_extra_quorum,
0 as btc_leadgen_item,
0 as regions_level_searches,
0 as cnt_fav_s_distr,
0 as iv_pro_image,
0 as filters_pr_rubr_searches,
0 as cnt_btc_premium
from DMA.buyer_stream ss
left join /*+jtype(h),distrib(l,a)*/ DDS.S_EngineRecommendation_Name en ON en.EngineRecommendation_id = ss.rec_engine_id
left join /*+jtype(h),distrib(l,a)*/ DMA.current_microcategories cmx on cmx.microcat_id = ss.x_microcat_id
left join /*+jtype(h),distrib(l,a)*/ DMA.current_microcategories cm on cm.microcat_id = ss.microcat_id
left join /*+jtype(h),distrib(l,a)*/ dict.segmentation_ranks ls on cm.logical_category_id = ls.logical_category_id and is_default
left join /*+jtype(h),distrib(l,a)*/ DMA.current_locations clx on clx.Location_id = ss.x_location_id
left join /*+jtype(h),distrib(l,a)*/ DMA.current_locations cl on cl.Location_id = ss.location_id

left join /*+jtype(fm),distrib(l,a)*/ (
    select first_action_track_id as track_id, first_action_event_no as event_no
    from DMA.user_btc_birthday
    where first_action_event_date::date between :first_date::date and :last_date::date
        and action_type = 'btc'
) ubb on ubb.track_id = ss.track_id and ubb.event_no = ss.event_no

left join /*+jtype(h),distrib(l,a)*/ (
    select
        usm.user_id,
        usm.logical_category_id,
        usm.user_segment as user_segment_market,
        c.event_date
    from (
        select
            user_id,
            logical_category_id,
            user_segment,
            converting_date as from_date,
            lead(converting_date, 1, '20990101') over(partition by user_id, logical_category_id order by converting_date) as to_date
        from DMA.user_segment_market
        where user_id in (select user_id from bs_users)
            and converting_date <= :last_date::date
    ) usm
    join dict.calendar c on c.event_date between :first_date::date and :last_date::date
    where c.event_date between usm.from_date and usm.to_date
        and usm.to_date >= :first_date::date
) usm on ss.item_user_id = usm.user_id and cm.logical_category_id = usm.logical_category_id and ss.event_date::date = usm.event_date

left join /*+jtype(h),distrib(l,a)*/ (
   select
        asd.user_id,
        (asd.personal_manager_team is not null and asd.user_is_asd_recognised) as is_asd,
        asd.user_group_id as asd_user_group_id,
        c.event_date
    from DMA.am_client_day_versioned asd
    join dict.calendar c on c.event_date between :first_date::date and :last_date::date
    where c.event_date between asd.active_to_date and asd.active_to_date
        and asd.active_from_date <= :last_date::date
        and asd.active_to_date >= :first_date::date
        and asd.user_id in (select user_id from bs_users)
) asd on ss.item_user_id = asd.user_id and ss.event_date::date = asd.event_date

left join /*+jtype(h),distrib(l,b)*/ (
    select
        user_id,
        max(COALESCE(SFAccount_Type, SFTopParentAccount_type))::varchar(128) as SFAccount_Type
    from DMA.salesforce_usermapping
    where COALESCE(SFAccount_Type, SFTopParentAccount_type) is not null
        and user_id in (select user_id from bs_users)
    group by user_id
) acc on acc.User_id = ss.item_user_id

where ss.event_date::date between :first_date and :last_date
