observation_strings = {
    (): """is_search, is_1p as searches,
is_search, is_1p, q as searches_with_query,
is_search, is_1p, noq as searches_without_query,
is_search, is_1p, is_s_sort_date as searches_date_sort,
is_search, is_1p, is_s_sort_price as searches_price_sort,
is_search, is_1p, is_s_sort_dft as searches_default_sort,
is_search, is_1p, q, is_s_sort_date as searches_with_query_date_sort,
is_search, is_1p, noq, is_s_sort_date as searches_without_query_date_sort,
is_search as searches_serp,
is_search, q as searches_query_serp,
is_search, is_1p, is_serp_empty as serp_empty,
is_search, is_1p, is_serp_small as serp_small,
is_search, is_1p, is_serp_empty, q as serp_with_query_empty,
is_search, is_1p, is_serp_small, q as serp_with_query_small,
is_search, is_1p, is_serp_empty, noq as serp_without_query_empty,
is_search, is_1p, is_serp_small, noq as serp_without_query_small,
is_search, x_is_rec_sg as searches_u2i,
is_search, is_1p, is_base_serp_empty as base_serp_empty,
is_search, is_1p, is_base_serp_small as base_serp_small,
is_search, is_1p, is_base_serp_empty, q as base_serp_with_query_empty,
is_search, is_1p, is_base_serp_small, q as base_serp_with_query_small,
is_search, is_1p, is_base_serp_empty, noq as base_serp_without_query_empty,
is_search, is_1p, is_base_serp_small, noq as base_serp_without_query_small,
is_search, is_1p, is_s_metro as searches_metro,
is_search, is_1p, is_s_district as searches_district,
is_search, is_1p, is_s_road as searches_road,
is_search, is_1p, is_s_radius as searches_radius,
is_search, is_1p, is_s_map as searches_map_area,
is_search, is_1p, is_s_saved as searches_saved,
is_search, is_1p, is_serp_ext_delivery as searches_extra_delivery,
is_search, is_1p, is_serp_ext_regions as searches_extra_regions,
is_search, is_serp_ext_delivery as searches_serp_extra_delivery,
is_search, is_serp_ext_regions as searches_serp_extra_regions,
is_search, is_serp_grouping as searches_group,
is_rec as recblock_shows,
is_i2i as recblock_shows_i2i,
is_u2i as recblock_shows_u2i,
is_fav_lst as favorites_list_views,
""" + """is_iv as item_views,
is_iv, is_item_vas as item_views_total_vas,
is_iv, is_item_vip as item_views_total_vip,
is_iv, is_item_premium as item_views_total_premium,
is_iv, is_item_push as item_views_total_push,
is_iv, x_is_search as item_views_search_item_attr,
is_ph, is_ph_right as phone_views_item_right,
is_ph, is_ph_top as phone_views_item_top,
is_ph, is_ph_snip as phone_views_snippet,
is_ph, is_ph_xlvas as phone_views_snippet_xlvas,
is_ph_tot as phone_views_total,
is_ph_tot, is_item_vas as phone_views_total_vas,
is_ph_tot, is_item_vip as phone_views_total_vip,
is_ph_tot, is_item_premium as phone_views_total_premium,
is_ph_tot, is_item_push as phone_views_total_push,
is_iv_client as item_views_client,
is_iv_client, x_is_rec_msg as item_views_client_rec_from_msg,
is_ph_chat as phone_views_in_chat,
is_msg_btn as write_button_clicks,
is_ph_btn as phone_view_button_clicks,
is_msg as first_messages,
is_msg, is_item_vas as first_messages_vas,
is_delivery_btn as delivery_flow_beginings,
is_delivery as delivery_order_created,
is_delivery, is_item_vas as delivery_order_created_vas,
is_booking as booking_created_short_rent,
is_booking, is_item_vas as booking_created_short_rent_vas,
is_btc, x_is_search as btc_search_item_attr,
is_contact, x_is_search as contacts_search_item_attr,
is_fav as favorites_added,
is_fav_rmv as favorites_removed,""",
    
('x'): """x_is_search, is_iv, is_serp_vas as searches_item_view_vas,
x_is_search, is_iv, is_serp_vip as searches_item_view_vip,
x_is_search, is_iv, is_serp_premium as searches_item_view_premium,
x_is_search, is_iv, is_serp_push as searches_item_view_push,
x_is_search, is_iv, is_serp_delivery as searches_item_view_delivery,
x_is_search, is_iv, is_serp_regions as searches_item_view_regions,
x_is_search, is_iv as searches_item_view_serp,
x_is_search, is_iv, x_is_rec_sg as searches_u2i_item_view,
x_is_rec, is_iv as shows_item_view_recblock,
x_is_fav_lst, is_iv as fav_list_item_view,
x_is_map, is_iv as map_searches_with_item_view,
x_is_search, is_iv, is_s_metro as searches_metro_with_item_view,
x_is_search, is_iv, is_s_district as searches_district_with_item_view,
x_is_search, is_iv, is_s_road as searches_road_with_item_view,
x_is_search, is_iv, is_s_radius as searches_radius_with_item_view,
x_is_search, is_iv, is_s_map as searches_map_area_with_item_view,
x_is_search, is_iv, is_s_saved as searches_saved_with_item_view,
x_is_search, is_iv, is_s_sort_date as searches_item_view_date_sort,
x_is_search, is_iv, is_s_sort_price as searches_item_view_price_sort,
x_is_search, is_iv, is_s_sort_dft as searches_item_view_default_sort,
x_is_search, is_iv, q as searches_query_item_view,
x_is_search, is_iv, noq as searches_noquery_item_view,
x_is_search, is_contact, is_serp_vas as searches_contact_vas,
x_is_search, is_contact, is_serp_vip as searches_contact_vip,
x_is_search, is_contact, is_serp_premium as searches_contact_premium,
x_is_search, is_contact, is_serp_push as searches_contact_push,
x_is_search, is_contact, is_serp_delivery as searches_contact_delivery,
x_is_search, is_contact, is_serp_regions as searches_contact_regions,
x_is_search, is_contact as searches_contact_serp,
x_is_search, is_contact, x_is_rec_sg as searches_u2i_contact,
x_is_search, is_contact, q as searches_query_contact,
x_is_search, is_contact, noq as searches_noquery_contact,
x_is_rec, is_contact as shows_contact_recblock,
x_is_fav_lst, is_contact as fav_list_contact,
x_is_map, is_contact as map_searches_with_contact,
x_is_search, is_contact, is_s_metro as searches_metro_with_contact,
x_is_search, is_contact, is_s_district as searches_district_with_contact,
x_is_search, is_contact, is_s_road as searches_road_with_contact,
x_is_search, is_contact, is_s_radius as searches_radius_with_contact,
x_is_search, is_contact, is_s_map as searches_map_area_with_contact,
x_is_search, is_contact, is_s_saved as searches_saved_with_contact,
x_is_search, is_btc, is_serp_vas as search_btc_vas,
x_is_search, is_btc, is_serp_vip as search_btc_vip,
x_is_search, is_btc, is_serp_premium as search_btc_premium,
x_is_search, is_btc, is_serp_push as search_btc_push,
x_is_search, is_btc, is_serp_delivery as search_btc_delivery,
x_is_search, is_btc, is_serp_regions as search_btc_regions,
x_is_search, is_btc as search_btc,
x_is_search, is_btc, x_is_rec_sg as searches_u2i_btc,
x_is_rec, is_btc as recshow_btc,
x_is_i2i, is_btc as recshow_btc_i2i,
x_is_u2i, is_btc as recshow_btc_u2i,
x_is_search, is_btc, is_s_sort_date as search_btc_date_sort,
x_is_search, is_btc, is_s_sort_price as search_btc_price_sort,
x_is_search, is_btc, is_s_sort_dft as search_btc_default_sort,
x_is_search, is_btc, q as search_btc_query,
x_is_search, is_btc, noq as search_btc_noquery,
x_is_map, is_btc as map_searches_with_btc,
x_is_search, is_btc, is_s_metro as searches_metro_with_btc,
x_is_search, is_btc, is_s_district as searches_district_with_btc,
x_is_search, is_btc, is_s_road as searches_road_with_btc,
x_is_search, is_btc, is_s_radius as searches_radius_with_btc,
x_is_search, is_btc, is_s_map as searches_map_area_with_btc,
x_is_search, is_btc, is_s_saved as searches_saved_with_btc""",

('x', 'item'): """x_is_search, is_iv_noguess, is_serp_vas as item_views_vas,
x_is_search, is_iv_noguess, is_serp_vip as item_views_vip,
x_is_search, is_iv_noguess, is_serp_premium as item_views_premium,
x_is_search, is_iv_noguess, is_serp_push as item_views_push,
x_is_search, is_iv_noguess, is_serp_delivery as item_views_delivery,
x_is_search, is_iv_noguess, is_serp_regions as item_views_regions,
x_is_search, is_iv_noguess as item_views_serp,
x_is_search, is_iv_noguess, x_is_rec_sg as item_views_searches_u2i,
x_is_search, is_iv_noguess, is_s_metro as item_views_serp_metro,
x_is_search, is_iv_noguess, is_s_district as item_views_serp_district,
x_is_search, is_iv_noguess, is_s_road as item_views_serp_road,
x_is_search, is_iv_noguess, is_s_radius as item_views_serp_radius,
x_is_search, is_iv_noguess, is_s_map as item_views_serp_map_area,
x_is_search, is_iv_noguess, is_s_saved as item_views_serp_saved,
x_is_search, is_serp_grouping, is_iv_noguess as item_views_grouped,
x_is_search, is_contact, is_serp_vas as contacts_vas,
x_is_search, is_contact, is_serp_vip as contacts_vip,
x_is_search, is_contact, is_serp_premium as contacts_premium,
x_is_search, is_contact, is_serp_push as contacts_push,
x_is_search, is_contact, is_serp_delivery as contacts_delivery,
x_is_search, is_contact, is_serp_regions as contacts_regions,
x_is_search, is_contact as contacts_serp,
x_is_search, is_contact, x_is_rec_sg as contacts_searches_u2i,
x_is_search, is_contact, is_s_metro as contacts_serp_metro,
x_is_search, is_contact, is_s_district as contacts_serp_district,
x_is_search, is_contact, is_s_road as contacts_serp_road,
x_is_search, is_contact, is_s_radius as contacts_serp_radius,
x_is_search, is_contact, is_s_map as contacts_serp_map_area,
x_is_search, is_contact, is_s_saved as contacts_serp_saved,
x_is_search, is_fav, is_serp_vas as fav_added_vas,
x_is_search, is_fav, is_serp_vip as fav_added_vip,
x_is_search, is_fav, is_serp_premium as fav_added_premium,
x_is_search, is_fav, is_serp_push as fav_added_push,
x_is_search, is_fav, is_serp_delivery as fav_added_delivery,
x_is_search, is_fav, is_serp_regions as fav_added_regions,
x_is_search, is_fav as fav_added_serp,
x_is_search, is_fav, x_is_rec_sg as fav_added_searches_u2i,
x_is_search, is_fav, is_s_metro as fav_added_serp_metro,
x_is_search, is_fav, is_s_district as fav_added_serp_district,
x_is_search, is_fav, is_s_road as fav_added_serp_road,
x_is_search, is_fav, is_s_radius as fav_added_serp_radius,
x_is_search, is_fav, is_s_map as fav_added_serp_map_area,
x_is_search, is_fav, is_s_saved as fav_added_serp_saved,
x_is_search, is_btc, is_serp_vas as buyer_target_clicks_vas,
x_is_search, is_btc, is_serp_vip as buyer_target_clicks_vip,
x_is_search, is_btc, is_serp_premium as buyer_target_clicks_premium,
x_is_search, is_btc, is_serp_push as buyer_target_clicks_push,
x_is_search, is_btc, is_serp_delivery as buyer_target_clicks_delivery,
x_is_search, is_btc, is_serp_regions as buyer_target_clicks_regions,
x_is_search, is_btc as buyer_target_clicks_serp,
x_is_search, is_btc, x_is_rec_sg as buyer_target_clicks_searches_u2i,
x_is_search, is_btc, is_s_metro as buyer_target_clicks_serp_metro,
x_is_search, is_btc, is_s_district as buyer_target_clicks_serp_district,
x_is_search, is_btc, is_s_road as buyer_target_clicks_serp_road,
x_is_search, is_btc, is_s_radius as buyer_target_clicks_serp_radius,
x_is_search, is_btc, is_s_map as buyer_target_clicks_serp_map_area,
x_is_search, is_btc, is_s_saved as buyer_target_clicks_serp_saved,
x_is_search, is_btc, is_s_sort_date as btc_serp_date_sort,
x_is_search, is_btc, is_s_sort_price as btc_serp_price_sort,
x_is_search, is_btc, is_s_sort_dft as btc_serp_default_sort,
x_is_search, is_btc, q as btc_serp_query,
x_is_search, is_btc, noq as btc_serp_noquery,
x_is_rec, is_iv_noguess as item_views_rec,
x_is_rec, is_iv_noguess, is_item_vas as item_views_rec_vas,
x_is_rec, is_iv_noguess, is_item_vip as item_views_rec_vip,
x_is_rec, is_iv_noguess, is_item_premium as item_views_rec_premium,
x_is_rec, is_iv_noguess, is_item_push as item_views_rec_push,
x_is_i2i, is_iv_noguess as item_views_rec_i2i,
x_is_i2i, is_iv_noguess, is_item_vas as item_views_rec_i2i_vas,
x_is_i2i, is_iv_noguess, is_item_vip as item_views_rec_i2i_vip,
x_is_i2i, is_iv_noguess, is_item_premium as item_views_rec_i2i_premium,
x_is_i2i, is_iv_noguess, is_item_push as item_views_rec_i2i_push,
x_is_u2i, is_iv_noguess as item_views_rec_u2i,
x_is_u2i, is_iv_noguess, is_item_vas as item_views_rec_u2i_vas,
x_is_u2i, is_iv_noguess, is_item_vip as item_views_rec_u2i_vip,
x_is_u2i, is_iv_noguess, is_item_premium as item_views_rec_u2i_premium,
x_is_u2i, is_iv_noguess, is_item_push as item_views_rec_u2i_push,
x_is_rec, is_contact as contacts_rec,
x_is_rec, is_contact, is_item_vas as contacts_rec_vas,
x_is_rec, is_contact, is_item_vip as contacts_rec_vip,
x_is_rec, is_contact, is_item_premium as contacts_rec_premium,
x_is_rec, is_contact, is_item_push as contacts_rec_push,
x_is_i2i, is_contact as contacts_rec_i2i,
x_is_i2i, is_contact, is_item_vas as contacts_rec_i2i_vas,
x_is_i2i, is_contact, is_item_vip as contacts_rec_i2i_vip,
x_is_i2i, is_contact, is_item_premium as contacts_rec_i2i_premium,
x_is_i2i, is_contact, is_item_push as contacts_rec_i2i_push,
x_is_u2i, is_contact as contacts_rec_u2i,
x_is_u2i, is_contact, is_item_vas as contacts_rec_u2i_vas,
x_is_u2i, is_contact, is_item_vip as contacts_rec_u2i_vip,
x_is_u2i, is_contact, is_item_premium as contacts_rec_u2i_premium,
x_is_u2i, is_contact, is_item_push as contacts_rec_u2i_push,
x_is_rec, is_fav as fav_added_rec,
x_is_rec, is_fav, is_item_vas as fav_added_rec_vas,
x_is_rec, is_fav, is_item_vip as fav_added_rec_vip,
x_is_rec, is_fav, is_item_premium as fav_added_rec_premium,
x_is_rec, is_fav, is_item_push as fav_added_rec_push,
x_is_i2i, is_fav as fav_added_rec_i2i,
x_is_i2i, is_fav, is_item_vas as fav_added_rec_i2i_vas,
x_is_i2i, is_fav, is_item_vip as fav_added_rec_i2i_vip,
x_is_i2i, is_fav, is_item_premium as fav_added_rec_i2i_premium,
x_is_i2i, is_fav, is_item_push as fav_added_rec_i2i_push,
x_is_u2i, is_fav as fav_added_rec_u2i,
x_is_u2i, is_fav, is_item_vas as fav_added_rec_u2i_vas,
x_is_u2i, is_fav, is_item_vip as fav_added_rec_u2i_vip,
x_is_u2i, is_fav, is_item_premium as fav_added_rec_u2i_premium,
x_is_u2i, is_fav, is_item_push as fav_added_rec_u2i_push,
x_is_rec, is_btc as buyer_target_clicks_rec,
x_is_rec, is_btc, is_item_vas as buyer_target_clicks_rec_vas,
x_is_rec, is_btc, is_item_vip as buyer_target_clicks_rec_vip,
x_is_rec, is_btc, is_item_premium as buyer_target_clicks_rec_premium,
x_is_rec, is_btc, is_item_push as buyer_target_clicks_rec_push,
x_is_i2i, is_btc as buyer_target_clicks_rec_i2i,
x_is_i2i, is_btc, is_item_vas as buyer_target_clicks_rec_i2i_vas,
x_is_i2i, is_btc, is_item_vip as buyer_target_clicks_rec_i2i_vip,
x_is_i2i, is_btc, is_item_premium as buyer_target_clicks_rec_i2i_premium,
x_is_i2i, is_btc, is_item_push as buyer_target_clicks_rec_i2i_push,
x_is_u2i, is_btc as buyer_target_clicks_rec_u2i,
x_is_u2i, is_btc, is_item_vas as buyer_target_clicks_rec_u2i_vas,
x_is_u2i, is_btc, is_item_vip as buyer_target_clicks_rec_u2i_vip,
x_is_u2i, is_btc, is_item_premium as buyer_target_clicks_rec_u2i_premium,
x_is_u2i, is_btc, is_item_push as buyer_target_clicks_rec_u2i_push,
x_is_fav_lst, is_iv_noguess as item_views_fav_list,
x_is_fav_lst, is_contact as contacts_fav_list,
x_is_map, is_iv_noguess as item_views_from_map,
x_is_map, is_contact as contacts_from_map,
x_is_map, is_fav as fav_added_from_map,
x_is_map, is_btc as buyer_target_clicks_from_map,"""}
